/**
 * Task 32 provider-free historical comparison.
 *
 * The baseline was generated by running this projection at audited commit
 * 524d09e81b00b08fe6af386011d34759a5e02fc0. Its exact source blob IDs and
 * unchanged fixture SHA-256s live beside the projection. Arrays are diffed by
 * index, and every allowlisted leaf pins both its audited and current value.
 *
 * `comparisonPackageLockBlob` pins the dependency tree this projection is
 * reproduced against, so a dependency change must be a reviewed edit rather
 * than a silent drift. It was rolled forward once, on 2026-09-01, for the
 * `browserslist` >=4.28.8 security override (GHSA-c83g-rgw3-j3cx /
 * GHSA-73wf-gq98-2v4g). That bump touches only a dev-time lint transitive
 * dependency: this test recomputes the projection from current source and
 * fixtures on every run, and it still matched the audited baseline byte for
 * byte afterwards, which is the evidence that the tree change altered no
 * pipeline output. Rolled forward a second time on 2026-09-01 when the lock
 * regained the `@emnapi/*` entries that npm on Windows had pruned (the reason
 * every CI `npm ci` failed); no package version changed and the projection
 * again matched the baseline byte for byte. Roll the pin forward again only
 * with the same evidence.
 */
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync } from "node:fs";
import path from "node:path";

import { afterEach, describe, expect, it, vi } from "vitest";

type JsonPrimitive = null | boolean | number | string;
type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };

interface BaselineDocument {
  provenance: {
    auditedBaseCommit: string;
    auditedBaseTree: string;
    sourceBlobs: Record<string, string>;
    fixtureHashes: { fmpTreeSha256: string; reportSha256: string };
    generator: {
      helperSha256: string;
      basePackageLockBlob: string;
      comparisonPackageLockBlob: string;
      generationNode: string;
      generationNpm: string;
      command: string;
    };
    fixedNow: string;
    generatedAt: string;
  };
  projection: JsonValue;
}

const ROOT = process.cwd();
const FMP_FIXTURE_ROOT = path.join(ROOT, "fixtures", "fmp");
const REPORT_FIXTURE = path.join(ROOT, "fixtures", "report", "DEMO-sample.json");
const BASELINE_PATH = path.join(
  ROOT,
  "tests",
  "fixtures",
  "audit-baseline-stageb-report.json",
);
const GENERATOR_PATH = path.join(ROOT, "tests", "helpers", "auditFixtureComparison.ts");
const FIXED_NOW = "2026-07-06T00:00:00.000Z";
const GENERATED_AT = "2026-07-06T12:00:00.000Z";
const AUDITED_BASE_TREE = "3210ac4f6e04a81e44ebdfd6989ecf721cb0e2a0";
const AUDITED_FMP_TREE_SHA256 =
  "2d4278a6d73453ea372bf655f299e9b8709b627098214ce5d0d3c2190aa3c7d9";
const AUDITED_REPORT_SHA256 =
  "e98dbece14978fa5662db016e002ab5b4706b24ac0cf5bbe0408c9f17c969c88";

type IntendedDelta =
  | { path: string; before: JsonValue; after: JsonValue }
  | { path: string; beforeMissing: true; after: JsonValue };

const OLD_RELATIVE_STRENGTH_NOTE =
  "Relative strength uses split-adjusted close-to-close price returns; dividends unavailable in the EOD feed, so figures approximate total return.";
const NEW_RELATIVE_STRENGTH_NOTE =
  "Relative strength uses split-adjusted close-to-close price return; dividends excluded.";
const OLD_BALANCE_BASIS =
  "latest annual FY 2025-12-31 revenue / invested capital (totalDebt + totalStockholdersEquity - cashAndShortTermInvestments, as of 2025-12-31)";
const NEW_BALANCE_BASIS =
  "latest annual FY 2025-12-31 revenue / invested capital (totalDebt + totalStockholdersEquity - cashAndShortTermInvestments, quarter balance as of 2025-12-31)";

const TERMINAL_ROIC_HOLD_NOTE =
  "terminal ROIC held at WACC: 2 fiscal years of ROIC on record, 4 needed to evidence durable excess returns (house rule)";
const NET_DEBT_NOTE =
  "NET_DEBT_V1: net debt -1300000000 as of 2025-12-31; totalDebt 1200000000, cashAndShortTermInvestments 2500000000";

const INTENDED_DELTAS: readonly IntendedDelta[] = [
  // Added 2026-09-01: fixture provenance strings are built with POSIX
  // separators so a Windows-generated baseline and a Linux CI runner agree on
  // the text. The baseline was generated on Windows, so every fixture path it
  // recorded carries backslashes; the current projection carries slashes. The
  // content of each string is otherwise identical.
  {
    path: "stageB.gaps.8.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\historicalMarketCap\\DEMO_2021-07-06_2026-07-06.json",
    after: "fixture:fixtures/fmp/historicalMarketCap/DEMO_2021-07-06_2026-07-06.json",
  },
  {
    path: "stageB.gaps.8.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\historicalMarketCap\\DEMO.json",
    after: "fixture:fixtures/fmp/historicalMarketCap/DEMO.json",
  },
  {
    path: "stageB.gaps.8.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\historicalMarketCap\\default.json",
    after: "fixture:fixtures/fmp/historicalMarketCap/default.json",
  },
  {
    path: "stageB.gaps.9.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\historicalPriceEodFull\\SPY_2021-07-06_2026-07-06.json",
    after: "fixture:fixtures/fmp/historicalPriceEodFull/SPY_2021-07-06_2026-07-06.json",
  },
  {
    path: "stageB.gaps.9.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\historicalPriceEodFull\\SPY.json",
    after: "fixture:fixtures/fmp/historicalPriceEodFull/SPY.json",
  },
  {
    path: "stageB.gaps.9.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\historicalPriceEodFull\\default.json",
    after: "fixture:fixtures/fmp/historicalPriceEodFull/default.json",
  },
  {
    path: "stageB.gaps.10.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\historicalPriceEodFull\\XLK_2021-07-06_2026-07-06.json",
    after: "fixture:fixtures/fmp/historicalPriceEodFull/XLK_2021-07-06_2026-07-06.json",
  },
  {
    path: "stageB.gaps.10.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\historicalPriceEodFull\\XLK.json",
    after: "fixture:fixtures/fmp/historicalPriceEodFull/XLK.json",
  },
  {
    path: "stageB.gaps.10.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\historicalPriceEodFull\\default.json",
    after: "fixture:fixtures/fmp/historicalPriceEodFull/default.json",
  },
  {
    path: "stageB.gaps.11.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\institutionalHolderAnalytics\\DEMO_2026_Q1.json",
    after: "fixture:fixtures/fmp/institutionalHolderAnalytics/DEMO_2026_Q1.json",
  },
  {
    path: "stageB.gaps.11.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\institutionalHolderAnalytics\\DEMO.json",
    after: "fixture:fixtures/fmp/institutionalHolderAnalytics/DEMO.json",
  },
  {
    path: "stageB.gaps.11.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\institutionalHolderAnalytics\\default.json",
    after: "fixture:fixtures/fmp/institutionalHolderAnalytics/default.json",
  },
  {
    path: "stageB.gaps.12.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\keyMetricsTtm\\DEMO.json",
    after: "fixture:fixtures/fmp/keyMetricsTtm/DEMO.json",
  },
  {
    path: "stageB.gaps.12.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\keyMetricsTtm\\default.json",
    after: "fixture:fixtures/fmp/keyMetricsTtm/default.json",
  },
  {
    path: "stageB.gaps.13.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\pressReleases\\DEMO.json",
    after: "fixture:fixtures/fmp/pressReleases/DEMO.json",
  },
  {
    path: "stageB.gaps.13.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\pressReleases\\default.json",
    after: "fixture:fixtures/fmp/pressReleases/default.json",
  },
  {
    path: "stageB.gaps.14.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\ratiosTtm\\DEMO.json",
    after: "fixture:fixtures/fmp/ratiosTtm/DEMO.json",
  },
  {
    path: "stageB.gaps.14.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\ratiosTtm\\default.json",
    after: "fixture:fixtures/fmp/ratiosTtm/default.json",
  },
  {
    path: "stageB.gaps.15.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\secFilingsSearch\\DEMO_2025-07-06_2026-07-06.json",
    after: "fixture:fixtures/fmp/secFilingsSearch/DEMO_2025-07-06_2026-07-06.json",
  },
  {
    path: "stageB.gaps.15.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\secFilingsSearch\\DEMO.json",
    after: "fixture:fixtures/fmp/secFilingsSearch/DEMO.json",
  },
  {
    path: "stageB.gaps.15.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\secFilingsSearch\\default.json",
    after: "fixture:fixtures/fmp/secFilingsSearch/default.json",
  },
  {
    path: "stageB.gaps.16.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\stockNews\\DEMO.json",
    after: "fixture:fixtures/fmp/stockNews/DEMO.json",
  },
  {
    path: "stageB.gaps.16.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\stockNews\\default.json",
    after: "fixture:fixtures/fmp/stockNews/default.json",
  },
  {
    path: "stageB.gaps.17.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\symbolPositionsSummary\\DEMO_2026_Q1.json",
    after: "fixture:fixtures/fmp/symbolPositionsSummary/DEMO_2026_Q1.json",
  },
  {
    path: "stageB.gaps.17.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\symbolPositionsSummary\\DEMO.json",
    after: "fixture:fixtures/fmp/symbolPositionsSummary/DEMO.json",
  },
  {
    path: "stageB.gaps.17.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\symbolPositionsSummary\\default.json",
    after: "fixture:fixtures/fmp/symbolPositionsSummary/default.json",
  },
  {
    path: "stageB.gaps.18.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\transcript\\DEMO_2025_Q4.json",
    after: "fixture:fixtures/fmp/transcript/DEMO_2025_Q4.json",
  },
  {
    path: "stageB.gaps.18.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\transcript\\DEMO.json",
    after: "fixture:fixtures/fmp/transcript/DEMO.json",
  },
  {
    path: "stageB.gaps.18.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\transcript\\default.json",
    after: "fixture:fixtures/fmp/transcript/default.json",
  },
  {
    path: "report.appendix.missingData.8.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\historicalMarketCap\\DEMO_2021-07-06_2026-07-06.json",
    after: "fixture:fixtures/fmp/historicalMarketCap/DEMO_2021-07-06_2026-07-06.json",
  },
  {
    path: "report.appendix.missingData.8.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\historicalMarketCap\\DEMO.json",
    after: "fixture:fixtures/fmp/historicalMarketCap/DEMO.json",
  },
  {
    path: "report.appendix.missingData.8.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\historicalMarketCap\\default.json",
    after: "fixture:fixtures/fmp/historicalMarketCap/default.json",
  },
  {
    path: "report.appendix.missingData.9.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\historicalPriceEodFull\\SPY_2021-07-06_2026-07-06.json",
    after: "fixture:fixtures/fmp/historicalPriceEodFull/SPY_2021-07-06_2026-07-06.json",
  },
  {
    path: "report.appendix.missingData.9.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\historicalPriceEodFull\\SPY.json",
    after: "fixture:fixtures/fmp/historicalPriceEodFull/SPY.json",
  },
  {
    path: "report.appendix.missingData.9.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\historicalPriceEodFull\\default.json",
    after: "fixture:fixtures/fmp/historicalPriceEodFull/default.json",
  },
  {
    path: "report.appendix.missingData.10.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\historicalPriceEodFull\\XLK_2021-07-06_2026-07-06.json",
    after: "fixture:fixtures/fmp/historicalPriceEodFull/XLK_2021-07-06_2026-07-06.json",
  },
  {
    path: "report.appendix.missingData.10.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\historicalPriceEodFull\\XLK.json",
    after: "fixture:fixtures/fmp/historicalPriceEodFull/XLK.json",
  },
  {
    path: "report.appendix.missingData.10.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\historicalPriceEodFull\\default.json",
    after: "fixture:fixtures/fmp/historicalPriceEodFull/default.json",
  },
  {
    path: "report.appendix.missingData.11.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\institutionalHolderAnalytics\\DEMO_2026_Q1.json",
    after: "fixture:fixtures/fmp/institutionalHolderAnalytics/DEMO_2026_Q1.json",
  },
  {
    path: "report.appendix.missingData.11.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\institutionalHolderAnalytics\\DEMO.json",
    after: "fixture:fixtures/fmp/institutionalHolderAnalytics/DEMO.json",
  },
  {
    path: "report.appendix.missingData.11.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\institutionalHolderAnalytics\\default.json",
    after: "fixture:fixtures/fmp/institutionalHolderAnalytics/default.json",
  },
  {
    path: "report.appendix.missingData.12.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\keyMetricsTtm\\DEMO.json",
    after: "fixture:fixtures/fmp/keyMetricsTtm/DEMO.json",
  },
  {
    path: "report.appendix.missingData.12.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\keyMetricsTtm\\default.json",
    after: "fixture:fixtures/fmp/keyMetricsTtm/default.json",
  },
  {
    path: "report.appendix.missingData.13.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\pressReleases\\DEMO.json",
    after: "fixture:fixtures/fmp/pressReleases/DEMO.json",
  },
  {
    path: "report.appendix.missingData.13.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\pressReleases\\default.json",
    after: "fixture:fixtures/fmp/pressReleases/default.json",
  },
  {
    path: "report.appendix.missingData.14.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\ratiosTtm\\DEMO.json",
    after: "fixture:fixtures/fmp/ratiosTtm/DEMO.json",
  },
  {
    path: "report.appendix.missingData.14.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\ratiosTtm\\default.json",
    after: "fixture:fixtures/fmp/ratiosTtm/default.json",
  },
  {
    path: "report.appendix.missingData.15.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\secFilingsSearch\\DEMO_2025-07-06_2026-07-06.json",
    after: "fixture:fixtures/fmp/secFilingsSearch/DEMO_2025-07-06_2026-07-06.json",
  },
  {
    path: "report.appendix.missingData.15.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\secFilingsSearch\\DEMO.json",
    after: "fixture:fixtures/fmp/secFilingsSearch/DEMO.json",
  },
  {
    path: "report.appendix.missingData.15.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\secFilingsSearch\\default.json",
    after: "fixture:fixtures/fmp/secFilingsSearch/default.json",
  },
  {
    path: "report.appendix.missingData.16.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\stockNews\\DEMO.json",
    after: "fixture:fixtures/fmp/stockNews/DEMO.json",
  },
  {
    path: "report.appendix.missingData.16.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\stockNews\\default.json",
    after: "fixture:fixtures/fmp/stockNews/default.json",
  },
  {
    path: "report.appendix.missingData.17.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\symbolPositionsSummary\\DEMO_2026_Q1.json",
    after: "fixture:fixtures/fmp/symbolPositionsSummary/DEMO_2026_Q1.json",
  },
  {
    path: "report.appendix.missingData.17.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\symbolPositionsSummary\\DEMO.json",
    after: "fixture:fixtures/fmp/symbolPositionsSummary/DEMO.json",
  },
  {
    path: "report.appendix.missingData.17.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\symbolPositionsSummary\\default.json",
    after: "fixture:fixtures/fmp/symbolPositionsSummary/default.json",
  },
  {
    path: "report.appendix.missingData.18.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\transcript\\DEMO_2025_Q4.json",
    after: "fixture:fixtures/fmp/transcript/DEMO_2025_Q4.json",
  },
  {
    path: "report.appendix.missingData.18.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\transcript\\DEMO.json",
    after: "fixture:fixtures/fmp/transcript/DEMO.json",
  },
  {
    path: "report.appendix.missingData.18.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\transcript\\default.json",
    after: "fixture:fixtures/fmp/transcript/default.json",
  },
  // Added 2026-08-31 (final pass): bestCagr now refuses a window whose
  // MEASURED span is not that window. This fixture's 3y and 5y revenue CAGRs
  // both span only 2.0 years, so the growth driver and the reverse-DCF
  // comparison now fall through to a window that was actually measured
  // instead of scoring a 2-year rate under a 5-year label.
  {
    path: "report.scores.aspects.fundamentals.drivers.0.value",
    before: 9.11,
    after: 8.7,
  },
  {
    path: "report.scores.aspects.fundamentals.drivers.2.value",
    before: 19,
    after: 17.8,
  },
  {
    path: "report.scores.aspects.fundamentals.score",
    before: 67.9,
    after: 67.13,
  },
  {
    path: "report.scores.aspects.valuation.drivers.1.value",
    before: -26.36,
    after: -25.94,
  },
  {
    path: "stageB.scores.aspects.fundamentals.drivers.0.value",
    before: 9.11,
    after: 8.7,
  },
  {
    path: "stageB.scores.aspects.fundamentals.drivers.2.value",
    before: 19,
    after: 17.8,
  },
  {
    path: "stageB.scores.aspects.fundamentals.score",
    before: 67.9,
    after: 67.13,
  },
  {
    path: "stageB.scores.aspects.valuation.drivers.1.value",
    before: -26.36,
    after: -25.94,
  },
  // Added 2026-08-31 (self-audit remediation): the quality and leadership
  // aspect notes are now route-aware. They advertised the ROIC-WACC spread
  // unconditionally after it had been suppressed on every financial route, so
  // a bank's report described a driver its own grade did not use.
  {
    path: "report.scores.aspects.leadership.note",
    before: "Capital-stewardship proxy (buyback discipline, capital deployment above cost, dilution). Qualitative leadership assessed in the analyst grade.",
    after: "Capital-stewardship proxy (buyback discipline, capital deployment above cost where the route scores it, dilution). Qualitative leadership assessed in the analyst grade.",
  },
  {
    path: "report.scores.aspects.quality.note",
    before: "Value creation (ROIC−WACC) and accounting integrity (Piotroski, Altman, accruals, Beneish).",
    after: "Value creation (ROIC−WACC, dropped where the route suppresses it — financial routes are costed on equity alone) and accounting integrity (Piotroski, plus Altman, accruals and Beneish where the route computes them — all three are withheld for financial classifications, whose balance sheets those models were not estimated on).",
  },
  {
    path: "stageB.scores.aspects.leadership.note",
    before: "Capital-stewardship proxy (buyback discipline, capital deployment above cost, dilution). Qualitative leadership assessed in the analyst grade.",
    after: "Capital-stewardship proxy (buyback discipline, capital deployment above cost where the route scores it, dilution). Qualitative leadership assessed in the analyst grade.",
  },
  {
    path: "stageB.scores.aspects.quality.note",
    before: "Value creation (ROIC−WACC) and accounting integrity (Piotroski, Altman, accruals, Beneish).",
    after: "Value creation (ROIC−WACC, dropped where the route suppresses it — financial routes are costed on equity alone) and accounting integrity (Piotroski, plus Altman, accruals and Beneish where the route computes them — all three are withheld for financial classifications, whose balance sheets those models were not estimated on).",
  },
  // Added 2026-08-31 (self-audit remediation): valueCompany now hoists the
  // multiples model's own gaps into the valuation manifest, mirroring the
  // excess-return and REIT hoists. The peers and ownHistory gaps were being
  // emitted and then dropped, so the peers disclosure added earlier never
  // actually reached the missing-data appendix.
  {
    path: "report.appendix.missingData.44",
    beforeMissing: true,
    after: {"field": "valuation.multiples.ownHistory", "reason": "insufficient history (need ≥8 quarters) to build own-history percentile bands (up to 5y)", "severity": "info"},
  },
  {
    path: "report.appendix.missingData.45",
    beforeMissing: true,
    after: {"field": "valuation.multiples.peers", "reason": "peer multiples not supplied to the valuation stage — peer medians unavailable (not evaluated)", "severity": "info"},
  },
  {
    path: "stageB.gaps.43",
    beforeMissing: true,
    after: {"field": "valuation.multiples.ownHistory", "reason": "insufficient history (need ≥8 quarters) to build own-history percentile bands (up to 5y)", "severity": "info"},
  },
  {
    path: "stageB.gaps.44",
    beforeMissing: true,
    after: {"field": "valuation.multiples.peers", "reason": "peer multiples not supplied to the valuation stage — peer medians unavailable (not evaluated)", "severity": "info"},
  },
  {
    path: "stageB.valuation.gaps.0",
    beforeMissing: true,
    after: {"field": "valuation.multiples.peers", "reason": "peer multiples not supplied to the valuation stage — peer medians unavailable (not evaluated)", "severity": "info"},
  },
  {
    path: "stageB.valuation.gaps.1",
    beforeMissing: true,
    after: {"field": "valuation.multiples.ownHistory", "reason": "insufficient history (need ≥8 quarters) to build own-history percentile bands (up to 5y)", "severity": "info"},
  },
  // Added 2026-08-31 (bank capital-return completion): financial routes now
  // score return on TANGIBLE COMMON EQUITY instead of ROIC, whose invested
  // capital is undefined for a deposit-funded balance sheet. The fixture
  // company is a general issuer, so only the moat note and the new
  // returns.rote block appear; its scored signals are unchanged.
  {
    path: "report.scores.aspects.moat.note",
    before: "Quantitative moat proxy: level and durability of ROIC plus gross-margin (pricing-power) level. Gross margin is dropped where the route suppresses it (banks, pre-revenue).",
    after: "Quantitative moat proxy: level and durability of ROIC plus gross-margin (pricing-power) level; financial routes score return on TANGIBLE COMMON EQUITY instead, since invested capital is undefined for a deposit-funded balance sheet. Gross margin is dropped where the route suppresses it (banks, pre-revenue).",
  },
  {
    path: "stageB.returns.rote",
    beforeMissing: true,
    after: {"series": [{"date": "2024-12-31", "rotePct": 40.54054054054054, "tangibleCommonEquity": 3700000000, "tangibleCommonEquityAvg": 3700000000}, {"date": "2025-12-31", "rotePct": 42.68292682926829, "tangibleCommonEquity": 4500000000, "tangibleCommonEquityAvg": 4100000000}], "latestRotePct": 42.68292682926829, "latestTangibleCommonEquity": 4500000000, "asOf": "2025-12-31", "notes": ["ROTE = net income / average tangible common equity (equity − goodwill − other intangibles − preferred)."], "gaps": []},
  },
  {
    path: "stageB.scores.aspects.moat.note",
    before: "Quantitative moat proxy: level and durability of ROIC plus gross-margin (pricing-power) level. Gross margin is dropped where the route suppresses it (banks, pre-revenue).",
    after: "Quantitative moat proxy: level and durability of ROIC plus gross-margin (pricing-power) level; financial routes score return on TANGIBLE COMMON EQUITY instead, since invested capital is undefined for a deposit-funded balance sheet. Gross margin is dropped where the route suppresses it (banks, pre-revenue).",
  },
  // Added 2026-08-31 (second audit pass): computeGrowth now folds CAGR
  // horizon shortfalls into GrowthResult.notes. The payload forwards
  // windowYears but never actualYears, so this fixture's 2.0-year span was
  // published and citable as both a 3-year and a 5-year CAGR.
  {
    path: "stageB.growth.notes.0",
    beforeMissing: true,
    after: "Revenue 3y CAGR is computed over 2.0 years (2023-12-31 → 2025-12-31) — the full 3-year history is unavailable; read it as that span, not as the labelled horizon.",
  },
  {
    path: "stageB.growth.notes.1",
    beforeMissing: true,
    after: "Revenue 5y CAGR is computed over 2.0 years (2023-12-31 → 2025-12-31) — the full 5-year history is unavailable; read it as that span, not as the labelled horizon.",
  },
  {
    path: "stageB.growth.notes.2",
    beforeMissing: true,
    after: "Revenue 10y CAGR is computed over 2.0 years (2023-12-31 → 2025-12-31) — the full 10-year history is unavailable; read it as that span, not as the labelled horizon.",
  },
  {
    path: "stageB.growth.notes.3",
    beforeMissing: true,
    after: "Diluted EPS 3y CAGR is computed over 2.0 years (2023-12-31 → 2025-12-31) — the full 3-year history is unavailable; read it as that span, not as the labelled horizon.",
  },
  {
    path: "stageB.growth.notes.4",
    beforeMissing: true,
    after: "Diluted EPS 5y CAGR is computed over 2.0 years (2023-12-31 → 2025-12-31) — the full 5-year history is unavailable; read it as that span, not as the labelled horizon.",
  },
  {
    path: "stageB.growth.notes.5",
    beforeMissing: true,
    after: "Diluted EPS 10y CAGR is computed over 2.0 years (2023-12-31 → 2025-12-31) — the full 10-year history is unavailable; read it as that span, not as the labelled horizon.",
  },
  {
    path: "stageB.growth.notes.6",
    beforeMissing: true,
    after: "Free cash flow 3y CAGR is computed over 1.0 years (2024-12-31 → 2025-12-31) — the full 3-year history is unavailable; read it as that span, not as the labelled horizon.",
  },
  {
    path: "stageB.growth.notes.7",
    beforeMissing: true,
    after: "Free cash flow 5y CAGR is computed over 1.0 years (2024-12-31 → 2025-12-31) — the full 5-year history is unavailable; read it as that span, not as the labelled horizon.",
  },
  {
    path: "stageB.growth.notes.8",
    beforeMissing: true,
    after: "Free cash flow 10y CAGR is computed over 1.0 years (2024-12-31 → 2025-12-31) — the full 10-year history is unavailable; read it as that span, not as the labelled horizon.",
  },
  // Added 2026-08-31 (second audit pass): multiplesFramework now emits an
  // explicit valuation.multiples.peers gap. Peer comparison is fully specified
  // and rendered downstream, but nothing ever populates `peers`, so a
  // permanently empty peer column read as "no comparable peers found" — a claim
  // about the market that was never evaluated. The new gap sorts first, which
  // shifts the pre-existing ownHistory gap down one index.
  {
    path: "stageB.valuation.multiples.gaps.0.field",
    before: "valuation.multiples.ownHistory",
    after: "valuation.multiples.peers",
  },
  {
    path: "stageB.valuation.multiples.gaps.0.reason",
    before: "insufficient history (need ≥8 quarters) to build own-history percentile bands (up to 5y)",
    after: "peer multiples not supplied to the valuation stage — peer medians unavailable (not evaluated)",
  },
  {
    path: "stageB.valuation.multiples.gaps.1",
    beforeMissing: true,
    after: {"field": "valuation.multiples.ownHistory", "reason": "insufficient history (need ≥8 quarters) to build own-history percentile bands (up to 5y)", "severity": "info"},
  },
  {
    path: "stageB.valuation.multiples.notes.0",
    before: "income-derived multiples use the latest ANNUAL statement — TTM was suppressed (incomplete quarterly data)",
    after: "Peer multiples are not supplied by the pipeline in this version — the peer median/IQR columns are unavailable for every multiple. This is a missing input, NOT a finding that the company has no peers.",
  },
  {
    path: "stageB.valuation.multiples.notes.1",
    before: "cash-flow-derived multiples use the latest ANNUAL statement — TTM was suppressed (incomplete quarterly data)",
    after: "income-derived multiples use the latest ANNUAL statement — TTM was suppressed (incomplete quarterly data)",
  },
  {
    path: "stageB.valuation.multiples.notes.2",
    beforeMissing: true,
    after: "cash-flow-derived multiples use the latest ANNUAL statement — TTM was suppressed (incomplete quarterly data)",
  },
  // Added 2026-08-31: range52w now reports whether the price history
  // actually spans 12 months, and nulls the range when it does not, so a
  // three-month high/low is never presented (or scored) as a 52-week one.
  // This fixture has full history, so only the new flag appears.
  {
    path: "stageB.technicals.range52w.insufficientHistory",
    beforeMissing: true,
    after: false,
  },
  // Added 2026-08-31 (second pass): multiplesFramework now emits an explicit
  // `valuation.multiples.peers` gap. Peer comparison is fully specified and
  // rendered downstream but nothing ever populates `peers`, so a permanently
  // empty peer column read as "no comparable peers found" — a claim about the
  // market that was never evaluated. The new gap is inserted first, which
  // shifts the existing ownHistory gap down one index.
  //
  // Added 2026-08-31: ROIC invested capital now nets cash + short-term
  // investments via the house net-debt resolver, instead of
  // cashAndCashEquivalents alone. The DCF's sales-to-capital basis string
  // (see OLD_BALANCE_BASIS above) already documented the cash + STI
  // definition, so one company carried two invested-capital conventions and
  // ROIC was understated for any issuer holding liquidity in T-bills or
  // commercial paper. This fixture's invested capital falls 4.80bn -> 4.40bn
  // and its ROIC rises 36.46% -> 40.06%, which flows into the ROIC-vs-WACC
  // spread and the quality/moat/leadership aspects and the composite.
  {
    path: "report.scores.aspects.leadership.drivers.0.value",
    before: 27.2,
    after: 30.81,
  },
  {
    path: "report.scores.aspects.moat.drivers.0.value",
    before: 36.46,
    after: 40.06,
  },
  {
    path: "report.scores.aspects.moat.drivers.1.value",
    before: 1.58,
    after: 1.86,
  },
  {
    path: "report.scores.aspects.moat.score",
    before: 86.65,
    after: 87.25,
  },
  {
    path: "report.scores.aspects.quality.drivers.0.value",
    before: 27.2,
    after: 30.81,
  },
  {
    path: "report.scores.composite.score",
    before: 77.59,
    after: 77.53,
  },
  {
    path: "stageB.returns.roic.latestRoicPct",
    before: 36.458333333333336,
    after: 40.06410256410257,
  },
  {
    path: "stageB.returns.roic.series.1.investedCapitalAvg",
    before: 4800000000,
    after: 4400000000,
  },
  {
    path: "stageB.returns.roic.series.1.roicPct",
    before: 33.30792682926829,
    after: 36.33592017738359,
  },
  {
    path: "stageB.returns.roic.series.2.investedCapitalAvg",
    before: 5000000000,
    after: 4550000000,
  },
  {
    path: "stageB.returns.roic.series.2.roicPct",
    before: 36.458333333333336,
    after: 40.06410256410257,
  },
  {
    path: "stageB.returns.roicVsWacc.note",
    before: "spread = ROIC 36.4583% − WACC 9.2559% (positive = returns above cost of capital)",
    after: "spread = ROIC 40.0641% − WACC 9.2559% (positive = returns above cost of capital)",
  },
  {
    path: "stageB.returns.roicVsWacc.spreadPctPts",
    before: 27.202387333333334,
    after: 30.808156564102568,
  },
  {
    path: "stageB.scores.aspects.leadership.drivers.0.value",
    before: 27.2,
    after: 30.81,
  },
  {
    path: "stageB.scores.aspects.moat.drivers.0.value",
    before: 36.46,
    after: 40.06,
  },
  {
    path: "stageB.scores.aspects.moat.drivers.1.value",
    before: 1.58,
    after: 1.86,
  },
  {
    path: "stageB.scores.aspects.moat.score",
    before: 86.65,
    after: 87.25,
  },
  {
    path: "stageB.scores.aspects.quality.drivers.0.value",
    before: 27.2,
    after: 30.81,
  },
  {
    path: "stageB.scores.composite.score",
    before: 77.59,
    after: 77.53,
  },
  // Added 2026-08-31: runForensics now aggregates the four models' own
  // house-rule notes into ForensicsReport.notes, mirroring the gaps
  // aggregation it already performed. These caveats - the Altman variant
  // rationale, the Z-double-prime X5 drop, the Hribar-Collins TATA
  // construction, Beneish's one-sided detection, and Sloan's lack of a
  // canonical bright line - were previously computed and then discarded, so
  // neither the reader nor the Stage C passes ever saw the conditions
  // attached to the forensic scores.
  {
    path: "stageB.forensics.notes.0",
    beforeMissing: true,
    after:
      "House heuristic: no SIC code available — manufacturer status inferred from sector/industry strings (non-manufacturer → Z″).",
  },
  {
    path: "stageB.forensics.notes.1",
    beforeMissing: true,
    after:
      "X5 (sales/TA) is dropped by the Z″ model to remove industry asset-turnover effects.",
  },
  {
    path: "stageB.forensics.notes.2",
    beforeMissing: true,
    after:
      "TATA uses the cash-flow construction (NI from continuing ops − CFO)/TA_t (Hribar–Collins 2002); balance-sheet construction reported as diagnostic only.",
  },
  {
    path: "stageB.forensics.notes.3",
    beforeMissing: true,
    after:
      "Diagnostic balance-sheet TATA uses shortTermDebt as a proxy for current maturities of LTD (broader — includes notes payable).",
  },
  {
    path: "stageB.forensics.notes.4",
    beforeMissing: true,
    after:
      "The model detects overstatement, not understatement — a very negative M does not prove conservative accounting.",
  },
  {
    path: "stageB.forensics.notes.5",
    beforeMissing: true,
    after:
      "ΔLEVER: prior-year average TA proxied by end-of-year TA (no t−2 balance sheet) — annotated proxy.",
  },
  {
    path: "stageB.forensics.notes.6",
    beforeMissing: true,
    after:
      "House-rule bands: |ratio| < 10% unremarkable, 10–20% elevated, > 20% red flag (heuristic — Sloan 1996 is a decile-ranking result with no canonical bright line).",
  },
  {
    path: "report.appendix.missingData.22.reason",
    before: "no SPY benchmark history supplied",
    after: "no valid SPY closes supplied for relative-strength alignment",
  },
  {
    path: "stageB.gaps.22.reason",
    before: "no SPY benchmark history supplied",
    after: "no valid SPY closes supplied for relative-strength alignment",
  },
  {
    path: "stageB.notes.0",
    before:
      "insufficient historical coverage: only 3 quarterly statement(s) available (< 8), but verified ipoDate 2015-01-02 is older than 24 months — treated as incomplete data coverage, NOT a recent-IPO overlay (audit 2026-07-11 finding #4). Long-window CAGRs/technicals degrade via their own insufficiency flags.",
    after:
      "TTM net income unavailable — unprofitable overlay evaluated on the latest annual net income (as of 2025-12-31).",
  },
  {
    path: "stageB.notes.1",
    beforeMissing: true,
    after:
      "TTM operating cash flow unavailable — unprofitable overlay evaluated on the latest annual OCF (as of 2025-12-31).",
  },
  {
    path: "stageB.notes.2",
    beforeMissing: true,
    after:
      "TTM revenue unavailable — latest annual revenue selected as the pre-revenue fallback observation.",
  },
  {
    path: "stageB.notes.3",
    beforeMissing: true,
    after:
      "insufficient historical coverage: only 3 quarterly statement(s) available (< 8), but verified ipoDate 2015-01-02 is older than 24 months — treated as incomplete data coverage, NOT a recent-IPO overlay (audit 2026-07-11 finding #4). Long-window CAGRs/technicals degrade via their own insufficiency flags.",
  },
  {
    path: "stageB.route.asOf.cashflowTtm",
    before: "2025-12-31",
    after: null,
  },
  {
    path: "stageB.route.asOf.incomeTtm",
    before: "2025-12-31",
    after: null,
  },
  {
    path: "stageB.route.notes.0",
    before:
      "insufficient historical coverage: only 3 quarterly statement(s) available (< 8), but verified ipoDate 2015-01-02 is older than 24 months — treated as incomplete data coverage, NOT a recent-IPO overlay (audit 2026-07-11 finding #4). Long-window CAGRs/technicals degrade via their own insufficiency flags.",
    after:
      "TTM net income unavailable — unprofitable overlay evaluated on the latest annual net income (as of 2025-12-31).",
  },
  {
    path: "stageB.route.notes.1",
    beforeMissing: true,
    after:
      "TTM operating cash flow unavailable — unprofitable overlay evaluated on the latest annual OCF (as of 2025-12-31).",
  },
  {
    path: "stageB.route.notes.2",
    beforeMissing: true,
    after:
      "TTM revenue unavailable — latest annual revenue selected as the pre-revenue fallback observation.",
  },
  {
    path: "stageB.route.notes.3",
    beforeMissing: true,
    after:
      "insufficient historical coverage: only 3 quarterly statement(s) available (< 8), but verified ipoDate 2015-01-02 is older than 24 months — treated as incomplete data coverage, NOT a recent-IPO overlay (audit 2026-07-11 finding #4). Long-window CAGRs/technicals degrade via their own insufficiency flags.",
  },
  // Added 2026-09-02 (WS5, D-16): the route result now carries the REIT
  // equity-vs-mortgage sub-map, because SIC 6798 covers both types and the two
  // maps disagree about which metrics mean anything. DEMO is a Technology
  // issuer on the general route, so the decision is null and no routing note
  // moves; only the new leaf appears.
  {
    path: "stageB.route.reitSubmap",
    beforeMissing: true,
    after: null,
  },
  // Added 2026-09-02 (WS5, D-17): route metrics for financial companies. DEMO
  // is a Technology issuer on the general route, which has none, so the block
  // is present and empty — the shape appears, no figure moves.
  {
    path: "stageB.financialMetrics",
    beforeMissing: true,
    after: { route: "general", metrics: [], notes: [], gaps: [], asOf: null },
  },
  // Added 2026-09-02 (WS5, D-17): the Piotroski result carries the scale it was
  // scored on, so a 3-of-3 financial variant is never read against the 9-point
  // scale. DEMO is non-financial, so it is the standard variant and the score
  // itself is unchanged — only the label is new.
  {
    path: "stageB.forensics.piotroski.variant",
    beforeMissing: true,
    after: "standard",
  },
  {
    path: "stageB.forensics.piotroski.label",
    beforeMissing: true,
    after: "Piotroski F (7 signals)",
  },
  {
    path: "report.valuation.dcf.assumptions.3.basis",
    before: OLD_BALANCE_BASIS,
    after: NEW_BALANCE_BASIS,
  },
  {
    path: "stageB.technicals.gaps.1.reason",
    before: "no SPY benchmark history supplied",
    after: "no valid SPY closes supplied for relative-strength alignment",
  },
  {
    path: "stageB.technicals.notes.1",
    before: OLD_RELATIVE_STRENGTH_NOTE,
    after: NEW_RELATIVE_STRENGTH_NOTE,
  },
  {
    path: "stageB.technicals.relativeStrength.benchmark.asOf",
    before: "2025-12-31",
    after: null,
  },
  {
    path: "stageB.technicals.relativeStrength.benchmark.gaps.0.reason",
    before: "no SPY benchmark history supplied",
    after: "no valid SPY closes supplied for relative-strength alignment",
  },
  {
    path: "stageB.technicals.relativeStrength.benchmark.notes.0",
    before: OLD_RELATIVE_STRENGTH_NOTE,
    after: NEW_RELATIVE_STRENGTH_NOTE,
  },
  {
    path: "stageB.technicals.relativeStrength.benchmark.points.0.endDate",
    beforeMissing: true,
    after: null,
  },
  {
    path: "stageB.technicals.relativeStrength.benchmark.points.0.startDate",
    beforeMissing: true,
    after: null,
  },
  {
    path: "stageB.technicals.relativeStrength.benchmark.points.0.symbolReturnPct",
    before: 6.496272630457933,
    after: null,
  },
  {
    path: "stageB.technicals.relativeStrength.benchmark.points.1.endDate",
    beforeMissing: true,
    after: null,
  },
  {
    path: "stageB.technicals.relativeStrength.benchmark.points.1.startDate",
    beforeMissing: true,
    after: null,
  },
  {
    path: "stageB.technicals.relativeStrength.benchmark.points.1.symbolReturnPct",
    before: 13.830392714854867,
    after: null,
  },
  {
    path: "stageB.technicals.relativeStrength.benchmark.points.2.endDate",
    beforeMissing: true,
    after: null,
  },
  {
    path: "stageB.technicals.relativeStrength.benchmark.points.2.startDate",
    beforeMissing: true,
    after: null,
  },
  {
    path: "stageB.technicals.relativeStrength.benchmark.points.2.symbolReturnPct",
    before: 31.492439184746868,
    after: null,
  },
  {
    path: "stageB.technicals.volumeTrend.avg20d",
    before: 1237500,
    after: 1237500.0000000002,
  },
  {
    path: "stageB.technicals.volumeTrend.avg90d",
    before: 1223611.111111111,
    after: 1223611.1111111108,
  },
  {
    path: "stageB.technicals.volumeTrend.ratio",
    before: 1.011350737797957,
    after: 1.0113507377979574,
  },
  {
    path: "stageB.valuation.assumptions.salesToCapital.basis",
    before: OLD_BALANCE_BASIS,
    after: NEW_BALANCE_BASIS,
  },
  // Added 2026-09-02 (terminal excess-return house rule): the DCF builder now
  // reads the annual ROIC series and, when ROIC beat WACC in each of the last
  // four-plus fiscal years, carries half the median spread (capped at 5pp)
  // into the terminal ROIC. This fixture has two fiscal years of ROIC, so the
  // default (terminal ROIC = WACC) holds and only the disclosure is new: the
  // assumption notes gain the hold reason, which also lands ahead of the
  // net-debt note in the valuation notes.
  {
    path: "stageB.valuation.assumptions.notes.1",
    beforeMissing: true,
    after: TERMINAL_ROIC_HOLD_NOTE,
  },
  {
    path: "stageB.valuation.notes.1",
    before: NET_DEBT_NOTE,
    after: TERMINAL_ROIC_HOLD_NOTE,
  },
  {
    path: "stageB.valuation.notes.2",
    beforeMissing: true,
    after: NET_DEBT_NOTE,
  },
];

const PROVIDER_ENV_KEYS = [
  "FMP_API_KEY",
  "FINNHUB_API_KEY",
  "FRED_API_KEY",
  "ANTHROPIC_API_KEY",
  "EDGAR_CONTACT",
] as const;

function generatorChildEnv(): NodeJS.ProcessEnv {
  const controlled = new Set([
    ...PROVIDER_ENV_KEYS.map((key) => key.toLowerCase()),
    "audit_fixture_emit",
    "audit_fixture_output",
    "node_options",
    "node_path",
  ]);
  const env: NodeJS.ProcessEnv = { ...process.env };
  for (const key of Object.keys(env)) {
    if (controlled.has(key.toLowerCase())) delete env[key];
  }
  env.AUDIT_FIXTURE_EMIT = "1";
  env.NODE_OPTIONS = "--conditions=react-server";
  env.NODE_PATH = path.join(ROOT, "node_modules");
  return env;
}

function sha256File(file: string): string {
  return createHash("sha256").update(readFileSync(file)).digest("hex");
}

function fixtureTreeSha256(root: string): string {
  const visit = (dir: string): string[] =>
    readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
      const absolute = path.join(dir, entry.name);
      return entry.isDirectory() ? visit(absolute) : [absolute];
    });
  const files = visit(root)
    .filter((file) => file.endsWith(".json"))
    .map((file) => path.relative(root, file).replaceAll("\\", "/"))
    .sort();
  const hash = createHash("sha256");
  for (const relative of files) {
    hash.update(relative);
    hash.update("\0");
    hash.update(readFileSync(path.join(root, ...relative.split("/"))));
    hash.update("\0");
  }
  return hash.digest("hex");
}

function loadBaseline(): BaselineDocument {
  return JSON.parse(readFileSync(BASELINE_PATH, "utf8")) as BaselineDocument;
}

function isRecord(value: JsonValue): value is { [key: string]: JsonValue } {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function diffPaths(before: JsonValue, after: JsonValue, prefix = ""): string[] {
  if (Array.isArray(before) && Array.isArray(after)) {
    const paths: string[] = [];
    const sharedLength = Math.min(before.length, after.length);
    for (let index = 0; index < sharedLength; index++) {
      paths.push(...diffPaths(before[index], after[index], `${prefix}.${index}`));
    }
    for (let index = sharedLength; index < Math.max(before.length, after.length); index++) {
      paths.push(`${prefix}.${index}`);
    }
    return paths;
  }
  if (Array.isArray(before) || Array.isArray(after)) return [prefix];
  if (isRecord(before) && isRecord(after)) {
    const keys = [...new Set([...Object.keys(before), ...Object.keys(after)])].sort();
    return keys.flatMap((key) => {
      const child = prefix.length > 0 ? `${prefix}.${key}` : key;
      if (!(key in before) || !(key in after)) return [child];
      return diffPaths(before[key], after[key], child);
    });
  }
  return Object.is(before, after) ? [] : [prefix];
}

function canonicalJson(value: JsonValue): string {
  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`;
  if (isRecord(value)) {
    return `{${Object.keys(value)
      .sort()
      .map((key) => `${JSON.stringify(key)}:${canonicalJson(value[key])}`)
      .join(",")}}`;
  }
  return JSON.stringify(value);
}

function readJsonPath(
  root: JsonValue,
  dottedPath: string,
): { exists: boolean; value: JsonValue | undefined } {
  let cursor: JsonValue = root;
  for (const key of dottedPath.split(".")) {
    if (Array.isArray(cursor)) {
      const index = Number(key);
      if (!Number.isInteger(index) || index < 0 || index >= cursor.length) {
        return { exists: false, value: undefined };
      }
      cursor = cursor[index];
      continue;
    }
    if (!isRecord(cursor) || !Object.hasOwn(cursor, key)) {
      return { exists: false, value: undefined };
    }
    cursor = cursor[key];
  }
  return { exists: true, value: cursor };
}

function assertExactDeltaContract(before: JsonValue, after: JsonValue): void {
  const actual = diffPaths(before, after).sort();
  const expected = INTENDED_DELTAS.map((delta) => delta.path).sort();
  if (JSON.stringify(actual) !== JSON.stringify(expected)) {
    throw new Error(
      `fixture delta contract mismatch\nexpected=${JSON.stringify(expected)}\nactual=${JSON.stringify(actual)}`,
    );
  }

  const reconstructed = structuredClone(before);
  for (const delta of INTENDED_DELTAS) {
    const baselineValue = readJsonPath(before, delta.path);
    if ("beforeMissing" in delta) {
      if (baselineValue.exists) {
        throw new Error(`expected audited path to be absent: ${delta.path}`);
      }
    } else if (
      !baselineValue.exists ||
      canonicalJson(baselineValue.value!) !== canonicalJson(delta.before)
    ) {
      throw new Error(`unexpected audited value at ${delta.path}`);
    }
    const currentValue = readJsonPath(after, delta.path);
    if (
      !currentValue.exists ||
      canonicalJson(currentValue.value!) !== canonicalJson(delta.after)
    ) {
      throw new Error(`unexpected current value at ${delta.path}`);
    }
    setJsonPath(reconstructed, delta.path, delta.after);
  }
  if (canonicalJson(reconstructed) !== canonicalJson(after)) {
    throw new Error("current projection differs from audited baseline plus exact intended deltas");
  }
}

function setJsonPath(root: JsonValue, dottedPath: string, value: JsonValue): void {
  const keys = dottedPath.split(".");
  let cursor = root;
  for (const key of keys.slice(0, -1)) {
    if (Array.isArray(cursor)) {
      const index = Number(key);
      if (!Number.isInteger(index) || index < 0 || index >= cursor.length) {
        throw new Error(`missing JSON path ${dottedPath}`);
      }
      cursor = cursor[index];
    } else {
      if (!isRecord(cursor) || !(key in cursor)) {
        throw new Error(`missing JSON path ${dottedPath}`);
      }
      cursor = cursor[key];
    }
  }
  const finalKey = keys.at(-1)!;
  if (Array.isArray(cursor)) {
    const index = Number(finalKey);
    if (!Number.isInteger(index) || index < 0 || index > cursor.length) {
      throw new Error(`missing JSON path ${dottedPath}`);
    }
    if (index === cursor.length) cursor.push(value);
    else cursor[index] = value;
  } else {
    if (!isRecord(cursor)) throw new Error(`non-object JSON parent ${dottedPath}`);
    cursor[finalKey] = value;
  }
}

afterEach(() => {
  vi.unstubAllEnvs();
  vi.unstubAllGlobals();
  vi.restoreAllMocks();
});

describe("Task 32 provider-free historical fixture comparison", () => {
  it("pins audited provenance, current fixture bytes, and the exact intended delta allowlist", async () => {
    const baseline = loadBaseline();
    expect(baseline.provenance).toMatchObject({
      auditedBaseCommit: "524d09e81b00b08fe6af386011d34759a5e02fc0",
      auditedBaseTree: AUDITED_BASE_TREE,
      fixedNow: FIXED_NOW,
      generatedAt: GENERATED_AT,
      fixtureHashes: {
        fmpTreeSha256: AUDITED_FMP_TREE_SHA256,
        reportSha256: AUDITED_REPORT_SHA256,
      },
      generator: {
        helperSha256: "73e890f2ec86463f5c86cb220e7ee65c8955ba4e0fdcbbc7eea6baff5e035bfe",
        basePackageLockBlob: "66f7242846b6d20cfe99e21400d2dada27bbfbfd",
        comparisonPackageLockBlob: "58d0f8390e3ee80281eec42f1dce8133f8d7daf2",
        generationNode: "v24.11.1",
        generationNpm: "11.6.2",
        command:
          "in detached 524d09e: npm ci; provider env blank; NODE_OPTIONS=--conditions=react-server; NODE_PATH=<base>/node_modules; AUDIT_FIXTURE_EMIT=1; node <base>/node_modules/tsx/dist/cli.mjs - < <remediation>/tests/helpers/auditFixtureComparison.ts",
      },
    });
    expect(baseline.provenance.sourceBlobs).toEqual({
      "src/pipeline/dataBundle.ts": "ca2efa5a8b191a45eb879142d5ec738777691eaf",
      "src/pipeline/compute.ts": "835d6dab9b892fbb9905fd3393a7600215e9c3ab",
      "src/pipeline/stageC/passes.ts": "11b36ed190e872c27621c0c79dbd34bb4a9b43da",
      "src/report/schema.ts": "891d66275b154aa2b4f1f1b32961382eaa0e72ad",
    });
    expect(
      execFileSync("git", ["hash-object", "package-lock.json"], {
        cwd: ROOT,
        encoding: "utf8",
      }).trim(),
    ).toBe(baseline.provenance.generator.comparisonPackageLockBlob);
    expect(sha256File(GENERATOR_PATH)).toBe(
      baseline.provenance.generator.helperSha256,
    );
    expect(fixtureTreeSha256(FMP_FIXTURE_ROOT)).toBe(AUDITED_FMP_TREE_SHA256);
    expect(sha256File(REPORT_FIXTURE)).toBe(AUDITED_REPORT_SHA256);

    for (const key of PROVIDER_ENV_KEYS) vi.stubEnv(key, "");
    vi.stubEnv("AUDIT_FIXTURE_EMIT", "");
    vi.stubEnv("AUDIT_FIXTURE_OUTPUT", "");
    const { assertAuditJsonSafe, buildAuditFixtureComparison } = await import(
      "./helpers/auditFixtureComparison"
    );
    const result = await buildAuditFixtureComparison({
      fmpFixtures: FMP_FIXTURE_ROOT,
      reportFixture: REPORT_FIXTURE,
    });
    const current = result.projection;
    expect(result.repeatedProjection).toEqual(current);
    const emitted = execFileSync(
      process.execPath,
      [path.join(ROOT, "node_modules", "tsx", "dist", "cli.mjs"), "-"],
      {
        cwd: ROOT,
        encoding: "utf8",
        env: generatorChildEnv(),
        input: readFileSync(GENERATOR_PATH, "utf8"),
        maxBuffer: 4 * 1024 * 1024,
        timeout: 20_000,
      },
    );
    expect(JSON.parse(emitted) as JsonValue).toEqual(current);
    expect(JSON.stringify(current)).toContain('"$auditUndefined":true');
    expect(() => assertAuditJsonSafe({ invalid: Number.NaN })).toThrow(
      /non-finite number.*invalid/,
    );
    expect(() => assertAuditJsonSafe({ invalid: undefined })).toThrow(
      /non-JSON undefined.*invalid/,
    );
    expect(() => assertAuditJsonSafe({ invalid: new Date(0) })).toThrow(
      /non-plain object.*invalid/,
    );
    expect(() => assertAuditJsonSafe({ invalid: new Map([["value", 1]]) })).toThrow(
      /non-plain object.*invalid/,
    );
    const decoratedArray = [1];
    Object.assign(decoratedArray, { extra: 2 });
    expect(() => assertAuditJsonSafe({ invalid: decoratedArray })).toThrow(
      /non-canonical array property.*invalid/,
    );
    assertExactDeltaContract(baseline.projection, current);
    expect(INTENDED_DELTAS.length).toBeGreaterThan(0);
    expect(result.calls).toMatchObject({
      globalFetch: 0,
      fmpLiveFetch: 0,
      finnhubLiveFetch: 0,
    });
    expect(result.calls.finraGapTransport).toBeGreaterThan(0);
    expect(result.calls.edgarGapTransport).toBeGreaterThan(0);
    expect(result.calls.fredGap).toBeGreaterThan(0);
    expect(result.reportCostUsd).toBe(0);
    expect(result.reportModel).toBe("synthetic-fixture");

    const unlistedDrift = structuredClone(current);
    setJsonPath(unlistedDrift, "fixtureControl.quotePrice", 41);
    expect(() => assertExactDeltaContract(baseline.projection, unlistedDrift)).toThrow(
      /fixtureControl\.quotePrice/,
    );

    const missingIntendedDelta = structuredClone(current);
    const baselineRatio = (baseline.projection as {
      stageB: { technicals: { volumeTrend: { ratio: JsonValue } } };
    }).stageB.technicals.volumeTrend.ratio;
    setJsonPath(
      missingIntendedDelta,
      "stageB.technicals.volumeTrend.ratio",
      baselineRatio,
    );
    expect(() =>
      assertExactDeltaContract(baseline.projection, missingIntendedDelta),
    ).toThrow(/stageB\.technicals\.volumeTrend\.ratio/);

    const arbitraryAllowedPathDrift = structuredClone(current);
    setJsonPath(
      arbitraryAllowedPathDrift,
      "stageB.technicals.volumeTrend.ratio",
      99,
    );
    expect(() =>
      assertExactDeltaContract(baseline.projection, arbitraryAllowedPathDrift),
    ).toThrow(/unexpected current value.*stageB\.technicals\.volumeTrend\.ratio/);
  }, 30_000);
});
