/**
 * Task 32 provider-free historical comparison.
 *
 * The baseline was generated by running this projection at audited commit
 * 524d09e81b00b08fe6af386011d34759a5e02fc0. Its exact source blob IDs and
 * unchanged fixture SHA-256s live beside the projection. Arrays are diffed by
 * index, and every allowlisted leaf pins both its audited and current value.
 *
 * The intended-delta list lives in `tests/fixtures/audit-intended-deltas.json`
 * and its machinery in `tests/helpers/auditDeltaContract.ts`. It left this file
 * when the remediation made it long enough that nobody would read it inline;
 * the guarantee is unchanged and gained a grouping that forces every blessed
 * leaf to carry a decision record and a reason. Regenerate with
 * `npm run audit:deltas -- --write --group <name>`.
 *
 * `comparisonPackageLockBlob` pins the dependency tree this projection is
 * reproduced against, so a dependency change must be a reviewed edit rather
 * than a silent drift. It was rolled forward once, on 2026-09-01, for the
 * `browserslist` >=4.28.8 security override (GHSA-c83g-rgw3-j3cx /
 * GHSA-73wf-gq98-2v4g). That bump touches only a dev-time lint transitive
 * dependency: this test recomputes the projection from current source and
 * fixtures on every run, and it still matched the audited baseline byte for
 * byte afterwards, which is the evidence that the tree change altered no
 * pipeline output. Rolled forward a second time on 2026-09-01 when the lock
 * regained the `@emnapi/*` entries that npm on Windows had pruned (the reason
 * every CI `npm ci` failed); no package version changed and the projection
 * again matched the baseline byte for byte. Roll the pin forward again only
 * with the same evidence.
 */
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync } from "node:fs";
import path from "node:path";

import { afterEach, describe, expect, it, vi } from "vitest";

import {
  type AuditJsonValue,
  type IntendedDeltaFile,
  assertExactDeltaContract,
  canonicalJson,
  computeManifestIdentity,
  flattenDeltaFile,
  setJsonPath,
} from "./helpers/auditDeltaContract";

type JsonValue = AuditJsonValue;

interface BaselineDocument {
  provenance: {
    auditedBaseCommit: string;
    auditedBaseTree: string;
    sourceBlobs: Record<string, string>;
    fixtureHashes: { fmpTreeSha256: string; reportSha256: string };
    generator: {
      helperSha256: string;
      basePackageLockBlob: string;
      comparisonPackageLockBlob: string;
      generationNode: string;
      generationNpm: string;
      command: string;
    };
    fixedNow: string;
    generatedAt: string;
  };
  projection: JsonValue;
}

const ROOT = process.cwd();
const FMP_FIXTURE_ROOT = path.join(ROOT, "fixtures", "fmp");
const REPORT_FIXTURE = path.join(ROOT, "fixtures", "report", "DEMO-sample.json");
const BASELINE_PATH = path.join(
  ROOT,
  "tests",
  "fixtures",
  "audit-baseline-stageb-report.json",
);
const GENERATOR_PATH = path.join(ROOT, "tests", "helpers", "auditFixtureComparison.ts");
const DELTA_PATH = path.join(ROOT, "tests", "fixtures", "audit-intended-deltas.json");
const FIXED_NOW = "2026-07-06T00:00:00.000Z";
const GENERATED_AT = "2026-07-06T12:00:00.000Z";
const AUDITED_BASE_TREE = "3210ac4f6e04a81e44ebdfd6989ecf721cb0e2a0";
const AUDITED_FMP_TREE_SHA256 =
  "2d4278a6d73453ea372bf655f299e9b8709b627098214ce5d0d3c2190aa3c7d9";
const AUDITED_REPORT_SHA256 =
  "e98dbece14978fa5662db016e002ab5b4706b24ac0cf5bbe0408c9f17c969c88";


const PROVIDER_ENV_KEYS = [
  "FMP_API_KEY",
  "FINNHUB_API_KEY",
  "FRED_API_KEY",
  "ANTHROPIC_API_KEY",
  "EDGAR_CONTACT",
] as const;

function generatorChildEnv(): NodeJS.ProcessEnv {
  const controlled = new Set([
    ...PROVIDER_ENV_KEYS.map((key) => key.toLowerCase()),
    "audit_fixture_emit",
    "audit_fixture_output",
    "node_options",
    "node_path",
  ]);
  const env: NodeJS.ProcessEnv = { ...process.env };
  for (const key of Object.keys(env)) {
    if (controlled.has(key.toLowerCase())) delete env[key];
  }
  env.AUDIT_FIXTURE_EMIT = "1";
  env.NODE_OPTIONS = "--conditions=react-server";
  env.NODE_PATH = path.join(ROOT, "node_modules");
  return env;
}

function sha256File(file: string): string {
  return createHash("sha256").update(readFileSync(file)).digest("hex");
}

function fixtureTreeSha256(root: string): string {
  const visit = (dir: string): string[] =>
    readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
      const absolute = path.join(dir, entry.name);
      return entry.isDirectory() ? visit(absolute) : [absolute];
    });
  const files = visit(root)
    .filter((file) => file.endsWith(".json"))
    .map((file) => path.relative(root, file).replaceAll("\\", "/"))
    .sort();
  const hash = createHash("sha256");
  for (const relative of files) {
    hash.update(relative);
    hash.update("\0");
    hash.update(readFileSync(path.join(root, ...relative.split("/"))));
    hash.update("\0");
  }
  return hash.digest("hex");
}

function loadBaseline(): BaselineDocument {
  return JSON.parse(readFileSync(BASELINE_PATH, "utf8")) as BaselineDocument;
}

function loadDeltaFile(): IntendedDeltaFile {
  return JSON.parse(readFileSync(DELTA_PATH, "utf8")) as IntendedDeltaFile;
}

afterEach(() => {
  vi.unstubAllEnvs();
  vi.unstubAllGlobals();
  vi.restoreAllMocks();
});

describe("Task 32 provider-free historical fixture comparison", () => {
  it("pins audited provenance, current fixture bytes, and the exact intended delta allowlist", async () => {
    const baseline = loadBaseline();
    const deltaFile = loadDeltaFile();
    const deltas = flattenDeltaFile(deltaFile);
    // The list is bound to this baseline: pairing it with a different audited
    // projection would let a stale "before" value pass unnoticed.
    expect(deltaFile.againstBaseline.auditedBaseCommit).toBe(
      "524d09e81b00b08fe6af386011d34759a5e02fc0",
    );
    expect(
      createHash("sha256").update(canonicalJson(baseline.projection)).digest("hex"),
    ).toBe(deltaFile.againstBaseline.projectionSha256);
    expect(baseline.provenance).toMatchObject({
      auditedBaseCommit: "524d09e81b00b08fe6af386011d34759a5e02fc0",
      auditedBaseTree: AUDITED_BASE_TREE,
      fixedNow: FIXED_NOW,
      generatedAt: GENERATED_AT,
      fixtureHashes: {
        fmpTreeSha256: AUDITED_FMP_TREE_SHA256,
        reportSha256: AUDITED_REPORT_SHA256,
      },
      generator: {
        helperSha256: "73e890f2ec86463f5c86cb220e7ee65c8955ba4e0fdcbbc7eea6baff5e035bfe",
        basePackageLockBlob: "66f7242846b6d20cfe99e21400d2dada27bbfbfd",
        comparisonPackageLockBlob: "58d0f8390e3ee80281eec42f1dce8133f8d7daf2",
        generationNode: "v24.11.1",
        generationNpm: "11.6.2",
        command:
          "in detached 524d09e: npm ci; provider env blank; NODE_OPTIONS=--conditions=react-server; NODE_PATH=<base>/node_modules; AUDIT_FIXTURE_EMIT=1; node <base>/node_modules/tsx/dist/cli.mjs - < <remediation>/tests/helpers/auditFixtureComparison.ts",
      },
    });
    expect(baseline.provenance.sourceBlobs).toEqual({
      "src/pipeline/dataBundle.ts": "ca2efa5a8b191a45eb879142d5ec738777691eaf",
      "src/pipeline/compute.ts": "835d6dab9b892fbb9905fd3393a7600215e9c3ab",
      "src/pipeline/stageC/passes.ts": "11b36ed190e872c27621c0c79dbd34bb4a9b43da",
      "src/report/schema.ts": "891d66275b154aa2b4f1f1b32961382eaa0e72ad",
    });
    expect(
      execFileSync("git", ["hash-object", "package-lock.json"], {
        cwd: ROOT,
        encoding: "utf8",
      }).trim(),
    ).toBe(baseline.provenance.generator.comparisonPackageLockBlob);
    expect(sha256File(GENERATOR_PATH)).toBe(
      baseline.provenance.generator.helperSha256,
    );
    expect(fixtureTreeSha256(FMP_FIXTURE_ROOT)).toBe(AUDITED_FMP_TREE_SHA256);
    expect(sha256File(REPORT_FIXTURE)).toBe(AUDITED_REPORT_SHA256);

    for (const key of PROVIDER_ENV_KEYS) vi.stubEnv(key, "");
    vi.stubEnv("AUDIT_FIXTURE_EMIT", "");
    vi.stubEnv("AUDIT_FIXTURE_OUTPUT", "");
    const { assertAuditJsonSafe, buildAuditFixtureComparison } = await import(
      "./helpers/auditFixtureComparison"
    );
    const result = await buildAuditFixtureComparison({
      fmpFixtures: FMP_FIXTURE_ROOT,
      reportFixture: REPORT_FIXTURE,
    });
    const current = result.projection;
    expect(result.repeatedProjection).toEqual(current);
    const emitted = execFileSync(
      process.execPath,
      [path.join(ROOT, "node_modules", "tsx", "dist", "cli.mjs"), "-"],
      {
        cwd: ROOT,
        encoding: "utf8",
        env: generatorChildEnv(),
        input: readFileSync(GENERATOR_PATH, "utf8"),
        maxBuffer: 4 * 1024 * 1024,
        timeout: 20_000,
      },
    );
    expect(JSON.parse(emitted) as JsonValue).toEqual(current);
    expect(JSON.stringify(current)).toContain('"$auditUndefined":true');
    expect(() => assertAuditJsonSafe({ invalid: Number.NaN })).toThrow(
      /non-finite number.*invalid/,
    );
    expect(() => assertAuditJsonSafe({ invalid: undefined })).toThrow(
      /non-JSON undefined.*invalid/,
    );
    expect(() => assertAuditJsonSafe({ invalid: new Date(0) })).toThrow(
      /non-plain object.*invalid/,
    );
    expect(() => assertAuditJsonSafe({ invalid: new Map([["value", 1]]) })).toThrow(
      /non-plain object.*invalid/,
    );
    const decoratedArray = [1];
    Object.assign(decoratedArray, { extra: 2 });
    expect(() => assertAuditJsonSafe({ invalid: decoratedArray })).toThrow(
      /non-canonical array property.*invalid/,
    );
    assertExactDeltaContract(baseline.projection, current, deltas);
    expect(deltas.length).toBeGreaterThan(0);
    // The same two manifests compared by entry name rather than by position:
    // an inserted gap entry shifts hundreds of leaves, and this is where a
    // reviewer sees which entries actually appeared, went away or changed.
    expect(
      computeManifestIdentity(baseline.projection, current, deltaFile.keyedArrays),
    ).toEqual(deltaFile.manifestIdentity);
    // Until D-11 the gap transports were exercised and counted here, which
    // proved the projection reached them without reaching the network. DEMO is
    // now a reserved fixture symbol, so no provider is consulted at all and
    // every counter must be exactly zero — a stronger statement than the
    // greater-than-zero one it replaces, and the reserved rule itself is
    // pinned by the manifest entry below.
    expect(result.calls).toEqual({
      globalFetch: 0,
      fmpLiveFetch: 0,
      finnhubLiveFetch: 0,
      finraGapTransport: 0,
      edgarGapTransport: 0,
      fredGap: 0,
    });
    expect(deltaFile.manifestIdentity["report.appendix.missingData"].added).toContain(
      "fixture.reserved(DEMO)",
    );
    expect(result.reportCostUsd).toBe(0);
    expect(result.reportModel).toBe("synthetic-fixture");

    const unlistedDrift = structuredClone(current);
    setJsonPath(unlistedDrift, "fixtureControl.quotePrice", 41);
    expect(() => assertExactDeltaContract(baseline.projection, unlistedDrift, deltas)).toThrow(
      /fixtureControl\.quotePrice/,
    );

    const missingIntendedDelta = structuredClone(current);
    const baselineRatio = (baseline.projection as {
      stageB: { technicals: { volumeTrend: { ratio: JsonValue } } };
    }).stageB.technicals.volumeTrend.ratio;
    setJsonPath(
      missingIntendedDelta,
      "stageB.technicals.volumeTrend.ratio",
      baselineRatio,
    );
    expect(() =>
      assertExactDeltaContract(baseline.projection, missingIntendedDelta, deltas),
    ).toThrow(/stageB\.technicals\.volumeTrend\.ratio/);

    const arbitraryAllowedPathDrift = structuredClone(current);
    setJsonPath(
      arbitraryAllowedPathDrift,
      "stageB.technicals.volumeTrend.ratio",
      99,
    );
    expect(() =>
      assertExactDeltaContract(baseline.projection, arbitraryAllowedPathDrift, deltas),
    ).toThrow(/unexpected current value.*stageB\.technicals\.volumeTrend\.ratio/);
  }, 30_000);
});
