/**
 * Task 32 provider-free historical comparison.
 *
 * The baseline was generated by running this projection at audited commit
 * 524d09e81b00b08fe6af386011d34759a5e02fc0. Its exact source blob IDs and
 * unchanged fixture SHA-256s live beside the projection. Arrays are diffed by
 * index, and every allowlisted leaf pins both its audited and current value.
 *
 * `comparisonPackageLockBlob` pins the dependency tree this projection is
 * reproduced against, so a dependency change must be a reviewed edit rather
 * than a silent drift. It was rolled forward once, on 2026-09-01, for the
 * `browserslist` >=4.28.8 security override (GHSA-c83g-rgw3-j3cx /
 * GHSA-73wf-gq98-2v4g). That bump touches only a dev-time lint transitive
 * dependency: this test recomputes the projection from current source and
 * fixtures on every run, and it still matched the audited baseline byte for
 * byte afterwards, which is the evidence that the tree change altered no
 * pipeline output. Rolled forward a second time on 2026-09-01 when the lock
 * regained the `@emnapi/*` entries that npm on Windows had pruned (the reason
 * every CI `npm ci` failed); no package version changed and the projection
 * again matched the baseline byte for byte. Roll the pin forward again only
 * with the same evidence.
 */
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync } from "node:fs";
import path from "node:path";

import { afterEach, describe, expect, it, vi } from "vitest";

type JsonPrimitive = null | boolean | number | string;
type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };

interface BaselineDocument {
  provenance: {
    auditedBaseCommit: string;
    auditedBaseTree: string;
    sourceBlobs: Record<string, string>;
    fixtureHashes: { fmpTreeSha256: string; reportSha256: string };
    generator: {
      helperSha256: string;
      basePackageLockBlob: string;
      comparisonPackageLockBlob: string;
      generationNode: string;
      generationNpm: string;
      command: string;
    };
    fixedNow: string;
    generatedAt: string;
  };
  projection: JsonValue;
}

const ROOT = process.cwd();
const FMP_FIXTURE_ROOT = path.join(ROOT, "fixtures", "fmp");
const REPORT_FIXTURE = path.join(ROOT, "fixtures", "report", "DEMO-sample.json");
const BASELINE_PATH = path.join(
  ROOT,
  "tests",
  "fixtures",
  "audit-baseline-stageb-report.json",
);
const GENERATOR_PATH = path.join(ROOT, "tests", "helpers", "auditFixtureComparison.ts");
const FIXED_NOW = "2026-07-06T00:00:00.000Z";
const GENERATED_AT = "2026-07-06T12:00:00.000Z";
const AUDITED_BASE_TREE = "3210ac4f6e04a81e44ebdfd6989ecf721cb0e2a0";
const AUDITED_FMP_TREE_SHA256 =
  "2d4278a6d73453ea372bf655f299e9b8709b627098214ce5d0d3c2190aa3c7d9";
const AUDITED_REPORT_SHA256 =
  "e98dbece14978fa5662db016e002ab5b4706b24ac0cf5bbe0408c9f17c969c88";

type IntendedDelta =
  | { path: string; before: JsonValue; after: JsonValue }
  | { path: string; beforeMissing: true; after: JsonValue };

const OLD_RELATIVE_STRENGTH_NOTE =
  "Relative strength uses split-adjusted close-to-close price returns; dividends unavailable in the EOD feed, so figures approximate total return.";
const NEW_RELATIVE_STRENGTH_NOTE =
  "Relative strength uses split-adjusted close-to-close price return; dividends excluded.";
const OLD_BALANCE_BASIS =
  "latest annual FY 2025-12-31 revenue / invested capital (totalDebt + totalStockholdersEquity - cashAndShortTermInvestments, as of 2025-12-31)";
const NEW_BALANCE_BASIS =
  "latest annual FY 2025-12-31 revenue / invested capital (totalDebt + totalStockholdersEquity - cashAndShortTermInvestments, quarter balance as of 2025-12-31)";

// TERMINAL_ROIC_HOLD_NOTE and NET_DEBT_NOTE were removed on 2026-09-02: WS6
// re-indexed the valuation notes those two entries pinned (the terminal-ROIC
// hold note is now followed by the sentence naming which cost of capital each
// ROIC year was measured against), and the regenerated entries carry the text
// inline. Their values are unchanged apart from "house rule" becoming "house
// convention" in the hold note.

const INTENDED_DELTAS: readonly IntendedDelta[] = [
  // Added 2026-09-01: fixture provenance strings are built with POSIX
  // separators so a Windows-generated baseline and a Linux CI runner agree on
  // the text. The baseline was generated on Windows, so every fixture path it
  // recorded carries backslashes; the current projection carries slashes. The
  // content of each string is otherwise identical.
  {
    path: "stageB.gaps.8.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\historicalMarketCap\\DEMO_2021-07-06_2026-07-06.json",
    after: "fixture:fixtures/fmp/historicalMarketCap/DEMO_2021-07-06_2026-07-06.json",
  },
  {
    path: "stageB.gaps.8.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\historicalMarketCap\\DEMO.json",
    after: "fixture:fixtures/fmp/historicalMarketCap/DEMO.json",
  },
  {
    path: "stageB.gaps.8.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\historicalMarketCap\\default.json",
    after: "fixture:fixtures/fmp/historicalMarketCap/default.json",
  },
  {
    path: "stageB.gaps.9.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\historicalPriceEodFull\\SPY_2021-07-06_2026-07-06.json",
    after: "fixture:fixtures/fmp/historicalPriceEodFull/SPY_2021-07-06_2026-07-06.json",
  },
  {
    path: "stageB.gaps.9.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\historicalPriceEodFull\\SPY.json",
    after: "fixture:fixtures/fmp/historicalPriceEodFull/SPY.json",
  },
  {
    path: "stageB.gaps.9.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\historicalPriceEodFull\\default.json",
    after: "fixture:fixtures/fmp/historicalPriceEodFull/default.json",
  },
  {
    path: "stageB.gaps.10.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\historicalPriceEodFull\\XLK_2021-07-06_2026-07-06.json",
    after: "fixture:fixtures/fmp/historicalPriceEodFull/XLK_2021-07-06_2026-07-06.json",
  },
  {
    path: "stageB.gaps.10.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\historicalPriceEodFull\\XLK.json",
    after: "fixture:fixtures/fmp/historicalPriceEodFull/XLK.json",
  },
  {
    path: "stageB.gaps.10.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\historicalPriceEodFull\\default.json",
    after: "fixture:fixtures/fmp/historicalPriceEodFull/default.json",
  },
  {
    path: "stageB.gaps.11.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\institutionalHolderAnalytics\\DEMO_2026_Q1.json",
    after: "fixture:fixtures/fmp/institutionalHolderAnalytics/DEMO_2026_Q1.json",
  },
  {
    path: "stageB.gaps.11.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\institutionalHolderAnalytics\\DEMO.json",
    after: "fixture:fixtures/fmp/institutionalHolderAnalytics/DEMO.json",
  },
  {
    path: "stageB.gaps.11.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\institutionalHolderAnalytics\\default.json",
    after: "fixture:fixtures/fmp/institutionalHolderAnalytics/default.json",
  },
  {
    path: "stageB.gaps.12.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\keyMetricsTtm\\DEMO.json",
    after: "fixture:fixtures/fmp/keyMetricsTtm/DEMO.json",
  },
  {
    path: "stageB.gaps.12.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\keyMetricsTtm\\default.json",
    after: "fixture:fixtures/fmp/keyMetricsTtm/default.json",
  },
  {
    path: "stageB.gaps.13.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\pressReleases\\DEMO.json",
    after: "fixture:fixtures/fmp/pressReleases/DEMO.json",
  },
  {
    path: "stageB.gaps.13.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\pressReleases\\default.json",
    after: "fixture:fixtures/fmp/pressReleases/default.json",
  },
  {
    path: "stageB.gaps.14.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\ratiosTtm\\DEMO.json",
    after: "fixture:fixtures/fmp/ratiosTtm/DEMO.json",
  },
  {
    path: "stageB.gaps.14.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\ratiosTtm\\default.json",
    after: "fixture:fixtures/fmp/ratiosTtm/default.json",
  },
  {
    path: "stageB.gaps.15.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\secFilingsSearch\\DEMO_2025-07-06_2026-07-06.json",
    after: "fixture:fixtures/fmp/secFilingsSearch/DEMO_2025-07-06_2026-07-06.json",
  },
  {
    path: "stageB.gaps.15.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\secFilingsSearch\\DEMO.json",
    after: "fixture:fixtures/fmp/secFilingsSearch/DEMO.json",
  },
  {
    path: "stageB.gaps.15.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\secFilingsSearch\\default.json",
    after: "fixture:fixtures/fmp/secFilingsSearch/default.json",
  },
  {
    path: "stageB.gaps.16.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\stockNews\\DEMO.json",
    after: "fixture:fixtures/fmp/stockNews/DEMO.json",
  },
  {
    path: "stageB.gaps.16.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\stockNews\\default.json",
    after: "fixture:fixtures/fmp/stockNews/default.json",
  },
  {
    path: "stageB.gaps.17.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\symbolPositionsSummary\\DEMO_2026_Q1.json",
    after: "fixture:fixtures/fmp/symbolPositionsSummary/DEMO_2026_Q1.json",
  },
  {
    path: "stageB.gaps.17.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\symbolPositionsSummary\\DEMO.json",
    after: "fixture:fixtures/fmp/symbolPositionsSummary/DEMO.json",
  },
  {
    path: "stageB.gaps.17.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\symbolPositionsSummary\\default.json",
    after: "fixture:fixtures/fmp/symbolPositionsSummary/default.json",
  },
  {
    path: "stageB.gaps.18.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\transcript\\DEMO_2025_Q4.json",
    after: "fixture:fixtures/fmp/transcript/DEMO_2025_Q4.json",
  },
  {
    path: "stageB.gaps.18.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\transcript\\DEMO.json",
    after: "fixture:fixtures/fmp/transcript/DEMO.json",
  },
  {
    path: "stageB.gaps.18.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\transcript\\default.json",
    after: "fixture:fixtures/fmp/transcript/default.json",
  },
  {
    path: "report.appendix.missingData.8.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\historicalMarketCap\\DEMO_2021-07-06_2026-07-06.json",
    after: "fixture:fixtures/fmp/historicalMarketCap/DEMO_2021-07-06_2026-07-06.json",
  },
  {
    path: "report.appendix.missingData.8.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\historicalMarketCap\\DEMO.json",
    after: "fixture:fixtures/fmp/historicalMarketCap/DEMO.json",
  },
  {
    path: "report.appendix.missingData.8.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\historicalMarketCap\\default.json",
    after: "fixture:fixtures/fmp/historicalMarketCap/default.json",
  },
  {
    path: "report.appendix.missingData.9.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\historicalPriceEodFull\\SPY_2021-07-06_2026-07-06.json",
    after: "fixture:fixtures/fmp/historicalPriceEodFull/SPY_2021-07-06_2026-07-06.json",
  },
  {
    path: "report.appendix.missingData.9.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\historicalPriceEodFull\\SPY.json",
    after: "fixture:fixtures/fmp/historicalPriceEodFull/SPY.json",
  },
  {
    path: "report.appendix.missingData.9.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\historicalPriceEodFull\\default.json",
    after: "fixture:fixtures/fmp/historicalPriceEodFull/default.json",
  },
  {
    path: "report.appendix.missingData.10.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\historicalPriceEodFull\\XLK_2021-07-06_2026-07-06.json",
    after: "fixture:fixtures/fmp/historicalPriceEodFull/XLK_2021-07-06_2026-07-06.json",
  },
  {
    path: "report.appendix.missingData.10.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\historicalPriceEodFull\\XLK.json",
    after: "fixture:fixtures/fmp/historicalPriceEodFull/XLK.json",
  },
  {
    path: "report.appendix.missingData.10.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\historicalPriceEodFull\\default.json",
    after: "fixture:fixtures/fmp/historicalPriceEodFull/default.json",
  },
  {
    path: "report.appendix.missingData.11.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\institutionalHolderAnalytics\\DEMO_2026_Q1.json",
    after: "fixture:fixtures/fmp/institutionalHolderAnalytics/DEMO_2026_Q1.json",
  },
  {
    path: "report.appendix.missingData.11.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\institutionalHolderAnalytics\\DEMO.json",
    after: "fixture:fixtures/fmp/institutionalHolderAnalytics/DEMO.json",
  },
  {
    path: "report.appendix.missingData.11.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\institutionalHolderAnalytics\\default.json",
    after: "fixture:fixtures/fmp/institutionalHolderAnalytics/default.json",
  },
  {
    path: "report.appendix.missingData.12.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\keyMetricsTtm\\DEMO.json",
    after: "fixture:fixtures/fmp/keyMetricsTtm/DEMO.json",
  },
  {
    path: "report.appendix.missingData.12.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\keyMetricsTtm\\default.json",
    after: "fixture:fixtures/fmp/keyMetricsTtm/default.json",
  },
  {
    path: "report.appendix.missingData.13.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\pressReleases\\DEMO.json",
    after: "fixture:fixtures/fmp/pressReleases/DEMO.json",
  },
  {
    path: "report.appendix.missingData.13.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\pressReleases\\default.json",
    after: "fixture:fixtures/fmp/pressReleases/default.json",
  },
  {
    path: "report.appendix.missingData.14.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\ratiosTtm\\DEMO.json",
    after: "fixture:fixtures/fmp/ratiosTtm/DEMO.json",
  },
  {
    path: "report.appendix.missingData.14.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\ratiosTtm\\default.json",
    after: "fixture:fixtures/fmp/ratiosTtm/default.json",
  },
  {
    path: "report.appendix.missingData.15.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\secFilingsSearch\\DEMO_2025-07-06_2026-07-06.json",
    after: "fixture:fixtures/fmp/secFilingsSearch/DEMO_2025-07-06_2026-07-06.json",
  },
  {
    path: "report.appendix.missingData.15.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\secFilingsSearch\\DEMO.json",
    after: "fixture:fixtures/fmp/secFilingsSearch/DEMO.json",
  },
  {
    path: "report.appendix.missingData.15.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\secFilingsSearch\\default.json",
    after: "fixture:fixtures/fmp/secFilingsSearch/default.json",
  },
  {
    path: "report.appendix.missingData.16.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\stockNews\\DEMO.json",
    after: "fixture:fixtures/fmp/stockNews/DEMO.json",
  },
  {
    path: "report.appendix.missingData.16.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\stockNews\\default.json",
    after: "fixture:fixtures/fmp/stockNews/default.json",
  },
  {
    path: "report.appendix.missingData.17.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\symbolPositionsSummary\\DEMO_2026_Q1.json",
    after: "fixture:fixtures/fmp/symbolPositionsSummary/DEMO_2026_Q1.json",
  },
  {
    path: "report.appendix.missingData.17.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\symbolPositionsSummary\\DEMO.json",
    after: "fixture:fixtures/fmp/symbolPositionsSummary/DEMO.json",
  },
  {
    path: "report.appendix.missingData.17.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\symbolPositionsSummary\\default.json",
    after: "fixture:fixtures/fmp/symbolPositionsSummary/default.json",
  },
  {
    path: "report.appendix.missingData.18.attemptedSources.1",
    before: "fixture:fixtures\\fmp\\transcript\\DEMO_2025_Q4.json",
    after: "fixture:fixtures/fmp/transcript/DEMO_2025_Q4.json",
  },
  {
    path: "report.appendix.missingData.18.attemptedSources.2",
    before: "fixture:fixtures\\fmp\\transcript\\DEMO.json",
    after: "fixture:fixtures/fmp/transcript/DEMO.json",
  },
  {
    path: "report.appendix.missingData.18.attemptedSources.3",
    before: "fixture:fixtures\\fmp\\transcript\\default.json",
    after: "fixture:fixtures/fmp/transcript/default.json",
  },
  // Added 2026-08-31 (final pass): bestCagr now refuses a window whose
  // MEASURED span is not that window. This fixture's 3y and 5y revenue CAGRs
  // both span only 2.0 years, so the growth driver and the reverse-DCF
  // comparison now fall through to a window that was actually measured
  // instead of scoring a 2-year rate under a 5-year label.
  {
    path: "report.scores.aspects.fundamentals.drivers.0.value",
    before: 9.11,
    after: 8.7,
  },
  {
    path: "report.scores.aspects.fundamentals.drivers.2.value",
    before: 19,
    after: 17.8,
  },
  {
    path: "report.scores.aspects.fundamentals.score",
    before: 67.9,
    after: 67.13,
  },
  {
    path: "report.scores.aspects.valuation.drivers.1.value",
    before: -26.36,
    after: -26.2,
  },
  {
    path: "stageB.scores.aspects.fundamentals.drivers.0.value",
    before: 9.11,
    after: 8.7,
  },
  {
    path: "stageB.scores.aspects.fundamentals.drivers.2.value",
    before: 19,
    after: 17.8,
  },
  {
    path: "stageB.scores.aspects.fundamentals.score",
    before: 67.9,
    after: 67.13,
  },
  {
    path: "stageB.scores.aspects.valuation.drivers.1.value",
    before: -26.36,
    after: -26.2,
  },
  // Added 2026-08-31 (self-audit remediation): the quality and leadership
  // aspect notes are now route-aware. They advertised the ROIC-WACC spread
  // unconditionally after it had been suppressed on every financial route, so
  // a bank's report described a driver its own grade did not use.
  {
    path: "report.scores.aspects.leadership.note",
    before: "Capital-stewardship proxy (buyback discipline, capital deployment above cost, dilution). Qualitative leadership assessed in the analyst grade.",
    after: "Capital-stewardship proxy (buyback discipline, capital deployment above cost where the route scores it, dilution). Qualitative leadership assessed in the analyst grade.",
  },
  {
    path: "report.scores.aspects.quality.note",
    before: "Value creation (ROIC−WACC) and accounting integrity (Piotroski, Altman, accruals, Beneish).",
    after: "Value creation (ROIC−WACC, dropped where the route suppresses it — financial routes are costed on equity alone) and accounting integrity (Piotroski, plus Altman, accruals and Beneish where the route computes them — all three are withheld for financial classifications, whose balance sheets those models were not estimated on).",
  },
  {
    path: "stageB.scores.aspects.leadership.note",
    before: "Capital-stewardship proxy (buyback discipline, capital deployment above cost, dilution). Qualitative leadership assessed in the analyst grade.",
    after: "Capital-stewardship proxy (buyback discipline, capital deployment above cost where the route scores it, dilution). Qualitative leadership assessed in the analyst grade.",
  },
  {
    path: "stageB.scores.aspects.quality.note",
    before: "Value creation (ROIC−WACC) and accounting integrity (Piotroski, Altman, accruals, Beneish).",
    after: "Value creation (ROIC−WACC, dropped where the route suppresses it — financial routes are costed on equity alone) and accounting integrity (Piotroski, plus Altman, accruals and Beneish where the route computes them — all three are withheld for financial classifications, whose balance sheets those models were not estimated on).",
  },
  // Added 2026-08-31 (self-audit remediation): valueCompany now hoists the
  // multiples model's own gaps into the valuation manifest, mirroring the
  // excess-return and REIT hoists. The peers and ownHistory gaps were being
  // emitted and then dropped, so the peers disclosure added earlier never
  // actually reached the missing-data appendix.
  {
    path: "report.appendix.missingData.44",
    beforeMissing: true,
    after: {"field":"valuation.dcf.terminalRoic.waccBasis","reason":"no per-fiscal-year risk-free observation was available, so the ROIC-vs-WACC evidence behind the terminal excess-return house convention compares every fiscal year to the CURRENT WACC","severity":"info"},
  },
  {
    path: "report.appendix.missingData.45",
    beforeMissing: true,
    after: {"field":"valuation.multiples.ownHistory","reason":"insufficient history (need ≥8 quarters) to rank the current multiple among the issuer's own quarters (window up to 5y)","severity":"info"},
  },
  {
    path: "stageB.gaps.43",
    beforeMissing: true,
    after: {"field":"valuation.dcf.terminalRoic.waccBasis","reason":"no per-fiscal-year risk-free observation was available, so the ROIC-vs-WACC evidence behind the terminal excess-return house convention compares every fiscal year to the CURRENT WACC","severity":"info"},
  },
  {
    path: "stageB.gaps.44",
    beforeMissing: true,
    after: {"field":"valuation.multiples.ownHistory","reason":"insufficient history (need ≥8 quarters) to rank the current multiple among the issuer's own quarters (window up to 5y)","severity":"info"},
  },
  {
    path: "stageB.valuation.gaps.0",
    beforeMissing: true,
    after: {"field": "valuation.multiples.peers", "reason": "peer multiples not supplied to the valuation stage — peer medians unavailable (not evaluated)", "severity": "info"},
  },
  {
    path: "stageB.valuation.gaps.1",
    beforeMissing: true,
    after: {"field":"valuation.multiples.ownHistory","reason":"insufficient history (need ≥8 quarters) to rank the current multiple among the issuer's own quarters (window up to 5y)","severity":"info"},
  },
  // Added 2026-08-31 (bank capital-return completion): financial routes now
  // score return on TANGIBLE COMMON EQUITY instead of ROIC, whose invested
  // capital is undefined for a deposit-funded balance sheet. The fixture
  // company is a general issuer, so only the moat note and the new
  // returns.rote block appear; its scored signals are unchanged.
  {
    path: "report.scores.aspects.moat.note",
    before: "Quantitative moat proxy: level and durability of ROIC plus gross-margin (pricing-power) level. Gross margin is dropped where the route suppresses it (banks, pre-revenue).",
    after: "Quantitative moat proxy: level and durability of ROIC plus gross-margin (pricing-power) level; financial routes score return on TANGIBLE COMMON EQUITY instead, since invested capital is undefined for a deposit-funded balance sheet. Gross margin is dropped where the route suppresses it (banks, pre-revenue).",
  },
  {
    path: "stageB.returns.rote",
    beforeMissing: true,
    after: {"series": [{"date": "2024-12-31", "rotePct": 40.54054054054054, "tangibleCommonEquity": 3700000000, "tangibleCommonEquityAvg": 3700000000}, {"date": "2025-12-31", "rotePct": 42.68292682926829, "tangibleCommonEquity": 4500000000, "tangibleCommonEquityAvg": 4100000000}], "latestRotePct": 42.68292682926829, "latestTangibleCommonEquity": 4500000000, "asOf": "2025-12-31", "notes": ["ROTE = net income / average tangible common equity (equity − goodwill − other intangibles − preferred)."], "gaps": []},
  },
  {
    path: "stageB.scores.aspects.moat.note",
    before: "Quantitative moat proxy: level and durability of ROIC plus gross-margin (pricing-power) level. Gross margin is dropped where the route suppresses it (banks, pre-revenue).",
    after: "Quantitative moat proxy: level and durability of ROIC plus gross-margin (pricing-power) level; financial routes score return on TANGIBLE COMMON EQUITY instead, since invested capital is undefined for a deposit-funded balance sheet. Gross margin is dropped where the route suppresses it (banks, pre-revenue).",
  },
  // Added 2026-08-31 (second audit pass): computeGrowth now folds CAGR
  // horizon shortfalls into GrowthResult.notes. The payload forwards
  // windowYears but never actualYears, so this fixture's 2.0-year span was
  // published and citable as both a 3-year and a 5-year CAGR.
  {
    path: "stageB.growth.notes.0",
    beforeMissing: true,
    after: "Revenue 3y CAGR is computed over 2.0 years (2023-12-31 → 2025-12-31) — the full 3-year history is unavailable; read it as that span, not as the labelled horizon.",
  },
  {
    path: "stageB.growth.notes.1",
    beforeMissing: true,
    after: "Revenue 5y CAGR is computed over 2.0 years (2023-12-31 → 2025-12-31) — the full 5-year history is unavailable; read it as that span, not as the labelled horizon.",
  },
  {
    path: "stageB.growth.notes.2",
    beforeMissing: true,
    after: "Revenue 10y CAGR is computed over 2.0 years (2023-12-31 → 2025-12-31) — the full 10-year history is unavailable; read it as that span, not as the labelled horizon.",
  },
  {
    path: "stageB.growth.notes.3",
    beforeMissing: true,
    after: "Diluted EPS 3y CAGR is computed over 2.0 years (2023-12-31 → 2025-12-31) — the full 3-year history is unavailable; read it as that span, not as the labelled horizon.",
  },
  {
    path: "stageB.growth.notes.4",
    beforeMissing: true,
    after: "Diluted EPS 5y CAGR is computed over 2.0 years (2023-12-31 → 2025-12-31) — the full 5-year history is unavailable; read it as that span, not as the labelled horizon.",
  },
  {
    path: "stageB.growth.notes.5",
    beforeMissing: true,
    after: "Diluted EPS 10y CAGR is computed over 2.0 years (2023-12-31 → 2025-12-31) — the full 10-year history is unavailable; read it as that span, not as the labelled horizon.",
  },
  {
    path: "stageB.growth.notes.6",
    beforeMissing: true,
    after: "Free cash flow 3y CAGR is computed over 1.0 years (2024-12-31 → 2025-12-31) — the full 3-year history is unavailable; read it as that span, not as the labelled horizon.",
  },
  {
    path: "stageB.growth.notes.7",
    beforeMissing: true,
    after: "Free cash flow 5y CAGR is computed over 1.0 years (2024-12-31 → 2025-12-31) — the full 5-year history is unavailable; read it as that span, not as the labelled horizon.",
  },
  {
    path: "stageB.growth.notes.8",
    beforeMissing: true,
    after: "Free cash flow 10y CAGR is computed over 1.0 years (2024-12-31 → 2025-12-31) — the full 10-year history is unavailable; read it as that span, not as the labelled horizon.",
  },
  // Added 2026-08-31 (second audit pass): multiplesFramework now emits an
  // explicit valuation.multiples.peers gap. Peer comparison is fully specified
  // and rendered downstream, but nothing ever populates `peers`, so a
  // permanently empty peer column read as "no comparable peers found" — a claim
  // about the market that was never evaluated. The new gap sorts first, which
  // shifts the pre-existing ownHistory gap down one index.
  {
    path: "stageB.valuation.multiples.gaps.0.field",
    before: "valuation.multiples.ownHistory",
    after: "valuation.multiples.peers",
  },
  {
    path: "stageB.valuation.multiples.gaps.0.reason",
    before: "insufficient history (need ≥8 quarters) to build own-history percentile bands (up to 5y)",
    after: "peer multiples not supplied to the valuation stage — peer medians unavailable (not evaluated)",
  },
  {
    path: "stageB.valuation.multiples.gaps.1",
    beforeMissing: true,
    after: {"field":"valuation.multiples.ownHistory","reason":"insufficient history (need ≥8 quarters) to rank the current multiple among the issuer's own quarters (window up to 5y)","severity":"info"},
  },
  {
    path: "stageB.valuation.multiples.notes.0",
    before: "income-derived multiples use the latest ANNUAL statement — TTM was suppressed (incomplete quarterly data)",
    after: "Enterprise value EXCLUDES lease liabilities (house default; set THESIS_EV_INCLUDE_LEASES=1 to include them). EV = market cap + total debt + preferred stock + minority interest − cash and short-term investments, less lease liabilities of 100000000 (already inside totalDebt under FMP's definition). EV/EBITDA uses this same EV; EBITDA is AFTER operating-lease cost (US GAAP ASC 842 keeps it in operating expenses), so excluding the lease liability from EV keeps numerator and denominator on the same basis. EV excluding leases 6600000000; EV including leases 6700000000.",
  },
  {
    path: "stageB.valuation.multiples.notes.1",
    before: "cash-flow-derived multiples use the latest ANNUAL statement — TTM was suppressed (incomplete quarterly data)",
    after: "Peer multiples are not supplied by the pipeline in this version — the peer median/IQR columns are unavailable for every multiple. This is a missing input, NOT a finding that the company has no peers.",
  },
  {
    path: "stageB.valuation.multiples.notes.2",
    beforeMissing: true,
    after: "income-derived multiples use the latest ANNUAL statement — TTM was suppressed (incomplete quarterly data)",
  },
  // Added 2026-08-31: range52w now reports whether the price history
  // actually spans 12 months, and nulls the range when it does not, so a
  // three-month high/low is never presented (or scored) as a 52-week one.
  // This fixture has full history, so only the new flag appears.
  {
    path: "stageB.technicals.range52w.insufficientHistory",
    beforeMissing: true,
    after: false,
  },
  // Added 2026-08-31 (second pass): multiplesFramework now emits an explicit
  // `valuation.multiples.peers` gap. Peer comparison is fully specified and
  // rendered downstream but nothing ever populates `peers`, so a permanently
  // empty peer column read as "no comparable peers found" — a claim about the
  // market that was never evaluated. The new gap is inserted first, which
  // shifts the existing ownHistory gap down one index.
  //
  // Added 2026-08-31: ROIC invested capital now nets cash + short-term
  // investments via the house net-debt resolver, instead of
  // cashAndCashEquivalents alone. The DCF's sales-to-capital basis string
  // (see OLD_BALANCE_BASIS above) already documented the cash + STI
  // definition, so one company carried two invested-capital conventions and
  // ROIC was understated for any issuer holding liquidity in T-bills or
  // commercial paper. This fixture's invested capital falls 4.80bn -> 4.40bn
  // and its ROIC rises 36.46% -> 40.06%, which flows into the ROIC-vs-WACC
  // spread and the quality/moat/leadership aspects and the composite.
  {
    path: "report.scores.aspects.leadership.drivers.0.value",
    before: 27.2,
    after: 30.81,
  },
  {
    path: "report.scores.aspects.moat.drivers.0.value",
    before: 36.46,
    after: 40.06,
  },
  {
    path: "report.scores.aspects.moat.drivers.1.value",
    before: 1.58,
    after: 1.86,
  },
  {
    path: "report.scores.aspects.moat.score",
    before: 86.65,
    after: 87.25,
  },
  {
    path: "report.scores.aspects.quality.drivers.0.value",
    before: 27.2,
    after: 30.81,
  },
  {
    path: "report.scores.composite.score",
    before: 77.59,
    after: 77.25,
  },
  {
    path: "stageB.returns.roic.latestRoicPct",
    before: 36.458333333333336,
    after: 40.06410256410257,
  },
  {
    path: "stageB.returns.roic.series.1.investedCapitalAvg",
    before: 4800000000,
    after: 4400000000,
  },
  {
    path: "stageB.returns.roic.series.1.roicPct",
    before: 33.30792682926829,
    after: 36.33592017738359,
  },
  {
    path: "stageB.returns.roic.series.2.investedCapitalAvg",
    before: 5000000000,
    after: 4550000000,
  },
  {
    path: "stageB.returns.roic.series.2.roicPct",
    before: 36.458333333333336,
    after: 40.06410256410257,
  },
  {
    path: "stageB.returns.roicVsWacc.note",
    before: "spread = ROIC 36.4583% − WACC 9.2559% (positive = returns above cost of capital)",
    after: "spread = ROIC 40.0641% − WACC 9.2559% (positive = returns above cost of capital)",
  },
  {
    path: "stageB.returns.roicVsWacc.spreadPctPts",
    before: 27.202387333333334,
    after: 30.808156564102568,
  },
  {
    path: "stageB.scores.aspects.leadership.drivers.0.value",
    before: 27.2,
    after: 30.81,
  },
  {
    path: "stageB.scores.aspects.moat.drivers.0.value",
    before: 36.46,
    after: 40.06,
  },
  {
    path: "stageB.scores.aspects.moat.drivers.1.value",
    before: 1.58,
    after: 1.86,
  },
  {
    path: "stageB.scores.aspects.moat.score",
    before: 86.65,
    after: 87.25,
  },
  {
    path: "stageB.scores.aspects.quality.drivers.0.value",
    before: 27.2,
    after: 30.81,
  },
  {
    path: "stageB.scores.composite.score",
    before: 77.59,
    after: 77.25,
  },
  // Added 2026-08-31: runForensics now aggregates the four models' own
  // house-rule notes into ForensicsReport.notes, mirroring the gaps
  // aggregation it already performed. These caveats - the Altman variant
  // rationale, the Z-double-prime X5 drop, the Hribar-Collins TATA
  // construction, Beneish's one-sided detection, and Sloan's lack of a
  // canonical bright line - were previously computed and then discarded, so
  // neither the reader nor the Stage C passes ever saw the conditions
  // attached to the forensic scores.
  {
    path: "stageB.forensics.notes.0",
    beforeMissing: true,
    after:
      "House heuristic: no SIC code available — manufacturer status inferred from sector/industry strings (non-manufacturer → Z″).",
  },
  {
    path: "stageB.forensics.notes.1",
    beforeMissing: true,
    after:
      "X5 (sales/TA) is dropped by the Z″ model to remove industry asset-turnover effects.",
  },
  {
    path: "stageB.forensics.notes.2",
    beforeMissing: true,
    after:
      "TATA uses the cash-flow construction (NI from continuing ops − CFO)/TA_t (Hribar–Collins 2002); balance-sheet construction reported as diagnostic only.",
  },
  {
    path: "stageB.forensics.notes.3",
    beforeMissing: true,
    after:
      "Diagnostic balance-sheet TATA uses shortTermDebt as a proxy for current maturities of LTD (broader — includes notes payable).",
  },
  {
    path: "stageB.forensics.notes.4",
    beforeMissing: true,
    after:
      "The model detects overstatement, not understatement — a very negative M does not prove conservative accounting.",
  },
  {
    path: "stageB.forensics.notes.5",
    beforeMissing: true,
    after:
      "ΔLEVER: prior-year average TA proxied by end-of-year TA (no t−2 balance sheet) — annotated proxy.",
  },
  {
    path: "stageB.forensics.notes.6",
    beforeMissing: true,
    after:
      "House-rule bands: |ratio| < 10% unremarkable, 10–20% elevated, > 20% red flag (heuristic — Sloan 1996 is a decile-ranking result with no canonical bright line).",
  },
  {
    path: "report.appendix.missingData.22.reason",
    before: "no SPY benchmark history supplied",
    after: "no valid SPY closes supplied for relative-strength alignment",
  },
  {
    path: "stageB.gaps.22.reason",
    before: "no SPY benchmark history supplied",
    after: "no valid SPY closes supplied for relative-strength alignment",
  },
  {
    path: "stageB.notes.0",
    before:
      "insufficient historical coverage: only 3 quarterly statement(s) available (< 8), but verified ipoDate 2015-01-02 is older than 24 months — treated as incomplete data coverage, NOT a recent-IPO overlay (audit 2026-07-11 finding #4). Long-window CAGRs/technicals degrade via their own insufficiency flags.",
    after:
      "TTM net income unavailable — unprofitable overlay evaluated on the latest annual net income (as of 2025-12-31).",
  },
  {
    path: "stageB.notes.1",
    beforeMissing: true,
    after:
      "TTM operating cash flow unavailable — unprofitable overlay evaluated on the latest annual OCF (as of 2025-12-31).",
  },
  {
    path: "stageB.notes.2",
    beforeMissing: true,
    after:
      "TTM revenue unavailable — latest annual revenue selected as the pre-revenue fallback observation.",
  },
  {
    path: "stageB.notes.3",
    beforeMissing: true,
    after:
      "insufficient historical coverage: only 3 quarterly statement(s) available (< 8), but verified ipoDate 2015-01-02 is older than 24 months — treated as incomplete data coverage, NOT a recent-IPO overlay (audit 2026-07-11 finding #4). Long-window CAGRs/technicals degrade via their own insufficiency flags.",
  },
  {
    path: "stageB.route.asOf.cashflowTtm",
    before: "2025-12-31",
    after: null,
  },
  {
    path: "stageB.route.asOf.incomeTtm",
    before: "2025-12-31",
    after: null,
  },
  {
    path: "stageB.route.notes.0",
    before:
      "insufficient historical coverage: only 3 quarterly statement(s) available (< 8), but verified ipoDate 2015-01-02 is older than 24 months — treated as incomplete data coverage, NOT a recent-IPO overlay (audit 2026-07-11 finding #4). Long-window CAGRs/technicals degrade via their own insufficiency flags.",
    after:
      "TTM net income unavailable — unprofitable overlay evaluated on the latest annual net income (as of 2025-12-31).",
  },
  {
    path: "stageB.route.notes.1",
    beforeMissing: true,
    after:
      "TTM operating cash flow unavailable — unprofitable overlay evaluated on the latest annual OCF (as of 2025-12-31).",
  },
  {
    path: "stageB.route.notes.2",
    beforeMissing: true,
    after:
      "TTM revenue unavailable — latest annual revenue selected as the pre-revenue fallback observation.",
  },
  {
    path: "stageB.route.notes.3",
    beforeMissing: true,
    after:
      "insufficient historical coverage: only 3 quarterly statement(s) available (< 8), but verified ipoDate 2015-01-02 is older than 24 months — treated as incomplete data coverage, NOT a recent-IPO overlay (audit 2026-07-11 finding #4). Long-window CAGRs/technicals degrade via their own insufficiency flags.",
  },
  // Added 2026-09-02 (WS5, D-16): the route result now carries the REIT
  // equity-vs-mortgage sub-map, because SIC 6798 covers both types and the two
  // maps disagree about which metrics mean anything. DEMO is a Technology
  // issuer on the general route, so the decision is null and no routing note
  // moves; only the new leaf appears.
  {
    path: "stageB.route.reitSubmap",
    beforeMissing: true,
    after: null,
  },
  // Added 2026-09-02 (WS5, D-17): route metrics for financial companies. DEMO
  // is a Technology issuer on the general route, which has none, so the block
  // is present and empty — the shape appears, no figure moves.
  {
    path: "stageB.financialMetrics",
    beforeMissing: true,
    after: { route: "general", metrics: [], notes: [], gaps: [], asOf: null },
  },
  // Added 2026-09-02 (WS5, D-17): the Piotroski result carries the scale it was
  // scored on, so a 3-of-3 financial variant is never read against the 9-point
  // scale. DEMO is non-financial, so it is the standard variant and the score
  // itself is unchanged — only the label is new.
  {
    path: "stageB.forensics.piotroski.variant",
    beforeMissing: true,
    after: "standard",
  },
  {
    path: "stageB.forensics.piotroski.label",
    beforeMissing: true,
    after: "Piotroski F (7 signals)",
  },
  {
    path: "report.valuation.dcf.assumptions.3.basis",
    before: "latest annual FY 2025-12-31 revenue / invested capital (totalDebt + totalStockholdersEquity - cashAndShortTermInvestments, as of 2025-12-31)",
    after: "linear fade over the explicit 10-year horizon from 9.11% (median of the available growth methods (log-linear revenue regression 9.1%, 3y revenue CAGR 9.11%, 5y revenue CAGR 9.11%, analyst-consensus case 7.89%)) to the terminal rate 2.5% in year 10; median of 4 available growth methods = 9.11%, range 7.89% to 9.11% — methods: log-linear revenue regression 9.1%/yr fitted over 3 annual years (2023-12-31 to 2025-12-31), R2 1; 3y revenue CAGR 9.11%; 5y revenue CAGR 9.11%; analyst-consensus case 7.89% (average implied growth over the next 2 fiscal years, through 2027-12-31) (house rule, WS6 D-18: median of methods; the former \"lower of the 3y/5y CAGR\" and sign-disagreement rules are RETIRED)",
  },
  {
    path: "stageB.technicals.gaps.1.reason",
    before: "no SPY benchmark history supplied",
    after: "no valid SPY closes supplied for relative-strength alignment",
  },
  {
    path: "stageB.technicals.notes.1",
    before: OLD_RELATIVE_STRENGTH_NOTE,
    after: NEW_RELATIVE_STRENGTH_NOTE,
  },
  {
    path: "stageB.technicals.relativeStrength.benchmark.asOf",
    before: "2025-12-31",
    after: null,
  },
  {
    path: "stageB.technicals.relativeStrength.benchmark.gaps.0.reason",
    before: "no SPY benchmark history supplied",
    after: "no valid SPY closes supplied for relative-strength alignment",
  },
  {
    path: "stageB.technicals.relativeStrength.benchmark.notes.0",
    before: OLD_RELATIVE_STRENGTH_NOTE,
    after: NEW_RELATIVE_STRENGTH_NOTE,
  },
  {
    path: "stageB.technicals.relativeStrength.benchmark.points.0.endDate",
    beforeMissing: true,
    after: null,
  },
  {
    path: "stageB.technicals.relativeStrength.benchmark.points.0.startDate",
    beforeMissing: true,
    after: null,
  },
  {
    path: "stageB.technicals.relativeStrength.benchmark.points.0.symbolReturnPct",
    before: 6.496272630457933,
    after: null,
  },
  {
    path: "stageB.technicals.relativeStrength.benchmark.points.1.endDate",
    beforeMissing: true,
    after: null,
  },
  {
    path: "stageB.technicals.relativeStrength.benchmark.points.1.startDate",
    beforeMissing: true,
    after: null,
  },
  {
    path: "stageB.technicals.relativeStrength.benchmark.points.1.symbolReturnPct",
    before: 13.830392714854867,
    after: null,
  },
  {
    path: "stageB.technicals.relativeStrength.benchmark.points.2.endDate",
    beforeMissing: true,
    after: null,
  },
  {
    path: "stageB.technicals.relativeStrength.benchmark.points.2.startDate",
    beforeMissing: true,
    after: null,
  },
  {
    path: "stageB.technicals.relativeStrength.benchmark.points.2.symbolReturnPct",
    before: 31.492439184746868,
    after: null,
  },
  {
    path: "stageB.technicals.volumeTrend.avg20d",
    before: 1237500,
    after: 1237500.0000000002,
  },
  {
    path: "stageB.technicals.volumeTrend.avg90d",
    before: 1223611.111111111,
    after: 1223611.1111111108,
  },
  {
    path: "stageB.technicals.volumeTrend.ratio",
    before: 1.011350737797957,
    after: 1.0113507377979574,
  },
  {
    path: "stageB.valuation.assumptions.salesToCapital.basis",
    before: OLD_BALANCE_BASIS,
    after: NEW_BALANCE_BASIS,
  },
  // Added 2026-09-02 (terminal excess-return house rule): the DCF builder now
  // reads the annual ROIC series and, when ROIC beat WACC in each of the last
  // four-plus fiscal years, carries half the median spread (capped at 5pp)
  // into the terminal ROIC. This fixture has two fiscal years of ROIC, so the
  // default (terminal ROIC = WACC) holds and only the disclosure is new: the
  // assumption notes gain the hold reason, which also lands ahead of the
  // net-debt note in the valuation notes.
  {
    path: "stageB.valuation.assumptions.notes.1",
    beforeMissing: true,
    after: "EBIT margin regime improving: dated 5y slope 1pp/year; target 20% versus current 20% and median 19%",
  },
  {
    path: "stageB.valuation.notes.1",
    before: "NET_DEBT_V1: net debt -1300000000 as of 2025-12-31; totalDebt 1200000000, cashAndShortTermInvestments 2500000000",
    after: "EBIT margin regime improving: dated 5y slope 1pp/year; target 20% versus current 20% and median 19%",
  },
  {
    path: "stageB.valuation.notes.2",
    beforeMissing: true,
    after: "terminal ROIC held at WACC: 2 fiscal years of ROIC on record, 4 needed to evidence durable excess returns (house convention)",
  },
  // ---- WS6 (valuation inputs and disclosure), 2026-09-02 ---- BEGIN
  // Added 2026-09-02 by WS6 (decisions D-18 / D-19). Every entry below follows
  // from methodology changes that are also stated in the DCF assumption block
  // and the missing-data manifest:
  //
  //  1. D-18 growth anchor: near-term growth is now the MEDIAN of the available
  //     methods (log-linear regression over all annual revenue years, 3y CAGR,
  //     5y CAGR, analyst-consensus case) with the range shown; "lower of the
  //     3y/5y CAGR" and the sign-disagreement rule are retired. On this fixture
  //     the anchor moves from the 3y CAGR alone to median(3y, 5y), so the DCF
  //     year rows, the sensitivity grid and the per-share value move with it.
  //     That is the point of the change, not a side effect.
  //  2. D-19 WACC disclosure: the assumption block and the report name the
  //     risk-free series and observation date, the ERP source and date, the
  //     cost-of-debt method, the tax-rate basis and the market-value E/D
  //     weights; the DCF assumption table gains a WACC row and a growth-anchor
  //     row, shifting the rows after them.
  //  3. D-19 per-year WACC: the ROIC-vs-WACC history recomputes the WACC at each
  //     fiscal year end from that year's risk-free observation. This fixture has
  //     no FRED observations, so the note says the current WACC was applied to
  //     every year and a returns.wacc.history info gap is disclosed.
  //  4. D-16 FCF/SBC, EV bridge and label changes carry the remaining entries;
  //     see docs/METHODOLOGY.md for each rule.
  //  5. Additive result fields: GrowthResult.revenueLogLinear, WaccResult
  //     riskFreeSeriesId / erpSource / erpAsOf / taxRateBasis, DcfAssumptions
  //     wacc / growthAnchor.
  {
    path: "report.appendix.missingData.46",
    beforeMissing: true,
    after: {"field":"valuation.multiples.peers","reason":"peer multiples not supplied to the valuation stage — peer medians unavailable (not evaluated)","severity":"info"},
  },
  {
    path: "report.fairValue.perShare.value",
    before: 146.23,
    after: 152.54,
  },
  {
    path: "report.fairValue.upsidePct",
    before: 265.575,
    after: 281.34999999999997,
  },
  {
    path: "report.meta.disclaimer",
    before: "Informational only — not investment advice.",
    after: "Informational only — not investment advice. This report contains A-F letter grades and scenario price targets; both are model outputs derived from the data and assumptions disclosed here, and neither is a recommendation to buy, sell, or hold any security.",
  },
  {
    path: "report.scores.aspects.balanceSheet.drivers.2.value",
    before: 1.03,
    after: 0.89,
  },
  {
    path: "report.scores.aspects.balanceSheet.score",
    before: 78.65,
    after: 76.78,
  },
  {
    path: "report.scores.aspects.valuation.drivers.0.value",
    before: 265.58,
    after: 281.35,
  },
  {
    path: "report.valuation.dcf.assumptions.1.basis",
    before: "linear fade from 7.89% (analyst consensus revenue, avg implied growth over next 2 fiscal years (through 2027-12-31)) to terminal 2.5% by year 10",
    after: "WACC 9.2559%: risk-free 4% (fmp:treasury-rates.year10, observation 2025-12-31); ERP 5% (FMP market-risk-premium (US totalEquityRiskPremium), as of 2026-07-06); beta 1.067 (Blume-adjusted (0.67·raw + 0.33), clamped [0.6, 2], raw 1.1); cost of equity 9.335%; pre-tax cost of debt 12% (effective); tax rate 27.0833% (FMP ratios effectiveTaxRate (observed effective rate)); E 86.4865% / D 13.5135% (market-value weights: equity = current market capitalization, debt = book totalDebt (average of the latest two balance sheets) as the market-value proxy)",
  },
  {
    path: "report.valuation.dcf.assumptions.1.name",
    before: "revenue growth (yr1 → yrN)",
    after: "WACC (discount rate)",
  },
  {
    path: "report.valuation.dcf.assumptions.1.value",
    before: "7.9% → 2.5%",
    after: "9.3%",
  },
  {
    path: "report.valuation.dcf.assumptions.2.basis",
    before: "held flat at current 20% under improving dated-margin regime (5y median 19%, slope 1pp/year)",
    after: "median of 4 available growth methods = 9.11%, range 7.89% to 9.11% — methods: log-linear revenue regression 9.1%/yr fitted over 3 annual years (2023-12-31 to 2025-12-31), R2 1; 3y revenue CAGR 9.11%; 5y revenue CAGR 9.11%; analyst-consensus case 7.89% (average implied growth over the next 2 fiscal years, through 2027-12-31) (house rule, WS6 D-18: median of methods; the former \"lower of the 3y/5y CAGR\" and sign-disagreement rules are RETIRED)",
  },
  {
    path: "report.valuation.dcf.assumptions.2.name",
    before: "EBIT margin (yr1 → yrN)",
    after: "near-term growth anchor (median of methods)",
  },
  {
    path: "report.valuation.dcf.assumptions.2.value",
    before: "20.0% → 20.0%",
    after: "9.1% (range 7.9% – 9.1%)",
  },
  {
    path: "report.valuation.dcf.assumptions.3.name",
    before: "sales-to-capital",
    after: "revenue growth (yr1 → yrN)",
  },
  {
    path: "report.valuation.dcf.assumptions.3.value",
    before: "2.66",
    after: "9.1% → 2.5%",
  },
  {
    path: "report.valuation.dcf.assumptions.4.basis",
    before: "min(2.5%, risk-free 4%) — house rule: nothing grows faster than rf forever",
    after: "held flat at current 20% under improving dated-margin regime (5y median 19%, slope 1pp/year)",
  },
  {
    path: "report.valuation.dcf.assumptions.4.name",
    before: "terminal growth",
    after: "EBIT margin (yr1 → yrN)",
  },
  {
    path: "report.valuation.dcf.assumptions.4.value",
    before: "2.5%",
    after: "20.0% → 20.0%",
  },
  {
    path: "report.valuation.dcf.assumptions.5.basis",
    before: "terminal ROIC = WACC (zero excess returns in perpetuity, house-rule default)",
    after: "latest annual FY 2025-12-31 revenue / invested capital (totalDebt + totalStockholdersEquity - cashAndShortTermInvestments, quarter balance as of 2025-12-31)",
  },
  {
    path: "report.valuation.dcf.assumptions.5.name",
    before: "terminal ROIC",
    after: "sales-to-capital",
  },
  {
    path: "report.valuation.dcf.assumptions.5.value",
    before: "9.3%",
    after: "2.66",
  },
  {
    path: "report.valuation.dcf.assumptions.6",
    beforeMissing: true,
    after: {"name":"terminal growth","value":"2.5%","basis":"min(2.5%, risk-free 4%) — house rule: nothing grows faster than rf forever"},
  },
  {
    path: "report.valuation.dcf.assumptions.7",
    beforeMissing: true,
    after: {"name":"terminal ROIC","value":"9.3%","basis":"terminal ROIC = WACC (zero excess returns in perpetuity, HOUSE CONVENTION default — see docs/METHODOLOGY.md, \"Terminal value house convention\"); ROIC-vs-WACC history compares every fiscal year to the CURRENT WACC 9.26% — no per-year risk-free observation was available to recompute a year-specific WACC"},
  },
  {
    path: "report.valuation.dcf.assumptions.8",
    beforeMissing: true,
    after: {"name":"free cash flow, SBC treatment","value":"1.80B → 1.55B","basis":"Stock-based compensation is expensed inside the EBIT this DCF projects, so it is never added back here; the reported free-cash-flow metric subtracts it as well (house default). The FCFF path derives from revenue, EBIT margin and reinvestment, not from the free-cash-flow metric, so the two are consistent but not the same series. Reported free cash flow as of 2025-12-31: 1800000000 before SBC → 1550000000 after subtracting SBC of 250000000."},
  },
  {
    path: "report.valuation.dcf.perShare.value",
    before: 146.23,
    after: 152.54,
  },
  {
    path: "report.valuation.dcf.sensitivityGrid.0.perShare",
    before: 166.376092292583,
    after: 173.8049998521903,
  },
  {
    path: "report.valuation.dcf.sensitivityGrid.1.perShare",
    before: 167.7149851175111,
    after: 175.22246130579066,
  },
  {
    path: "report.valuation.dcf.sensitivityGrid.10.perShare",
    before: 145.54397447067558,
    after: 151.8102954280996,
  },
  {
    path: "report.valuation.dcf.sensitivityGrid.11.perShare",
    before: 145.888476635414,
    after: 152.17501359680358,
  },
  {
    path: "report.valuation.dcf.sensitivityGrid.12.perShare",
    before: 146.23297880015247,
    after: 152.5397317655075,
  },
  {
    path: "report.valuation.dcf.sensitivityGrid.13.perShare",
    before: 146.57748096489092,
    after: 152.9044499342115,
  },
  {
    path: "report.valuation.dcf.sensitivityGrid.14.perShare",
    before: 146.92198312962938,
    after: 153.26916810291547,
  },
  {
    path: "report.valuation.dcf.sensitivityGrid.15.perShare",
    before: 137.02303327015306,
    after: 142.81822308027702,
  },
  {
    path: "report.valuation.dcf.sensitivityGrid.16.perShare",
    before: 137.07019569277645,
    after: 142.86815307831895,
  },
  {
    path: "report.valuation.dcf.sensitivityGrid.17.perShare",
    before: 137.07839478363584,
    after: 142.87683330651296,
  },
  {
    path: "report.valuation.dcf.sensitivityGrid.18.perShare",
    before: 137.03897964504117,
    after: 142.83510521700046,
  },
  {
    path: "report.valuation.dcf.sensitivityGrid.19.perShare",
    before: 136.940533723176,
    after: 142.7308823121421,
  },
  {
    path: "report.valuation.dcf.sensitivityGrid.2.perShare",
    before: 169.2211734983775,
    after: 176.81703551814675,
  },
  {
    path: "report.valuation.dcf.sensitivityGrid.20.perShare",
    before: 129.477139616909,
    after: 134.8577470549213,
  },
  {
    path: "report.valuation.dcf.sensitivityGrid.21.perShare",
    before: 129.31120340693457,
    after: 134.68207341098494,
  },
  {
    path: "report.valuation.dcf.sensitivityGrid.22.perShare",
    before: 129.08313762406544,
    after: 134.44062431955413,
  },
  {
    path: "report.valuation.dcf.sensitivityGrid.23.perShare",
    before: 128.78009840764705,
    after: 134.11980221922994,
  },
  {
    path: "report.valuation.dcf.sensitivityGrid.24.perShare",
    before: 128.38543965803257,
    after: 133.70198418742842,
  },
  {
    path: "report.valuation.dcf.sensitivityGrid.3.perShare",
    before: 170.9424020912171,
    after: 178.63926888721124,
  },
  {
    path: "report.valuation.dcf.sensitivityGrid.4.perShare",
    before: 172.94649343185347,
    after: 180.76096389666722,
  },
  {
    path: "report.valuation.dcf.sensitivityGrid.5.perShare",
    before: 155.24133879734714,
    after: 162.0471351684362,
  },
  {
    path: "report.valuation.dcf.sensitivityGrid.6.perShare",
    before: 156.0003561762538,
    after: 162.8506930463946,
  },
  {
    path: "report.valuation.dcf.sensitivityGrid.7.perShare",
    before: 156.82318027878264,
    after: 163.72180194078325,
  },
  {
    path: "report.valuation.dcf.sensitivityGrid.8.perShare",
    before: 157.72643914234646,
    after: 164.67806565202787,
  },
  {
    path: "report.valuation.dcf.sensitivityGrid.9.perShare",
    before: 158.73308812865395,
    after: 165.74378660357115,
  },
  {
    path: "report.valuation.dcf.upsidePct",
    before: 265.575,
    after: 281.34999999999997,
  },
  {
    path: "report.valuation.multiples.1.current",
    before: 2.392857142857143,
    after: 2.357142857142857,
  },
  {
    path: "report.valuation.multiples.2.current",
    before: 0.536,
    after: 0.528,
  },
  {
    path: "report.valuation.reverseDcf.impliedValue",
    before: -17.24609375,
    after: -17.5,
  },
  {
    path: "stageB.capital.dilution",
    beforeMissing: true,
    after: {"basicShares":200000000,"dilutedShares":205000000,"overhangPct":2.5,"asOf":"2025-12-31","note":"Dilution from outstanding awards: diluted 205000000 vs basic 200000000 weighted-average shares as of 2025-12-31 — a 2.5% overhang. Options, RSUs and convertibles that are antidilutive in a loss year are excluded from the diluted count by the filer, so a loss-making issuer's overhang understates the award pool."},
  },
  {
    path: "stageB.capital.fcf.basis",
    beforeMissing: true,
    after: "Free cash flow = operating cash flow + capital expenditure (FMP capex negative), MINUS stock-based compensation (house default: SBC is a cash-equivalent operating expense settled in shares, not a genuine add-back — Damodaran, \"Stock Based Compensation: The Elephant in the Room\"). Both the before- and after-SBC figures are reported; years with no disclosed SBC are unadjusted and say so.",
  },
  {
    path: "stageB.capital.fcf.latestConversion",
    before: 1.0285714285714285,
    after: 0.8857142857142857,
  },
  {
    path: "stageB.capital.fcf.latestFcf",
    before: 1800000000,
    after: 1550000000,
  },
  {
    path: "stageB.capital.fcf.latestFcfBeforeSbc",
    beforeMissing: true,
    after: 1800000000,
  },
  {
    path: "stageB.capital.fcf.latestSbc",
    beforeMissing: true,
    after: 250000000,
  },
  {
    path: "stageB.capital.fcf.series.0.fcf",
    before: 1550000000,
    after: 1330000000,
  },
  {
    path: "stageB.capital.fcf.series.0.fcfBeforeSbc",
    beforeMissing: true,
    after: 1550000000,
  },
  {
    path: "stageB.capital.fcf.series.0.fcfConversion",
    before: 1.0333333333333334,
    after: 0.8866666666666667,
  },
  {
    path: "stageB.capital.fcf.series.0.note",
    before: {"$auditUndefined":true},
    after: "SBC 220000000 subtracted from FCF (house default): 1550000000 → 1330000000",
  },
  {
    path: "stageB.capital.fcf.series.0.stockBasedCompensation",
    beforeMissing: true,
    after: 220000000,
  },
  {
    path: "stageB.capital.fcf.series.1.fcf",
    before: 1800000000,
    after: 1550000000,
  },
  {
    path: "stageB.capital.fcf.series.1.fcfBeforeSbc",
    beforeMissing: true,
    after: 1800000000,
  },
  {
    path: "stageB.capital.fcf.series.1.fcfConversion",
    before: 1.0285714285714285,
    after: 0.8857142857142857,
  },
  {
    path: "stageB.capital.fcf.series.1.note",
    before: {"$auditUndefined":true},
    after: "SBC 250000000 subtracted from FCF (house default): 1800000000 → 1550000000",
  },
  {
    path: "stageB.capital.fcf.series.1.stockBasedCompensation",
    beforeMissing: true,
    after: 250000000,
  },
  {
    path: "stageB.capital.notes.1",
    beforeMissing: true,
    after: "Dilution from outstanding awards: diluted 205000000 vs basic 200000000 weighted-average shares as of 2025-12-31 — a 2.5% overhang. Options, RSUs and convertibles that are antidilutive in a loss year are excluded from the diluted count by the filer, so a loss-making issuer's overhang understates the award pool.",
  },
  {
    path: "stageB.capital.notes.2",
    beforeMissing: true,
    after: "Free cash flow = operating cash flow + capital expenditure (FMP capex negative), MINUS stock-based compensation (house default: SBC is a cash-equivalent operating expense settled in shares, not a genuine add-back — Damodaran, \"Stock Based Compensation: The Elephant in the Room\"). Both the before- and after-SBC figures are reported; years with no disclosed SBC are unadjusted and say so.",
  },
  {
    path: "stageB.capital.notes.3",
    beforeMissing: true,
    after: "Latest free cash flow (2025-12-31): 1800000000 before SBC, 1550000000 after subtracting SBC of 250000000.",
  },
  {
    path: "stageB.capital.sbc.note",
    before: {"$auditUndefined":true},
    after: "SBC % of FCF is measured against FCF BEFORE the SBC deduction",
  },
  {
    path: "stageB.fairValue.perShare.value",
    before: 146.23,
    after: 152.54,
  },
  {
    path: "stageB.fairValue.upsidePct",
    before: 265.575,
    after: 281.34999999999997,
  },
  {
    path: "stageB.gaps.45",
    beforeMissing: true,
    after: {"field":"valuation.multiples.peers","reason":"peer multiples not supplied to the valuation stage — peer medians unavailable (not evaluated)","severity":"info"},
  },
  {
    path: "stageB.growth.revenueLogLinear",
    beforeMissing: true,
    after: {"growthPct":9.102622070718525,"slopePerYear":0.0871187402075796,"rSquared":0.9994077381522407,"n":3,"startDate":"2023-12-31","endDate":"2025-12-31","note":{"$auditUndefined":true}},
  },
  {
    path: "stageB.returns.notes.0",
    beforeMissing: true,
    after: "WACC 9.2559%: risk-free 4% (fmp:treasury-rates.year10, observation 2025-12-31); ERP 5% (FMP market-risk-premium (US totalEquityRiskPremium), as of 2026-07-06); beta 1.067 (Blume-adjusted (0.67·raw + 0.33), clamped [0.6, 2], raw 1.1); cost of equity 9.335%; pre-tax cost of debt 12% (effective); tax rate 27.0833% (FMP ratios effectiveTaxRate (observed effective rate)); E 86.4865% / D 13.5135% (market-value weights: equity = current market capitalization, debt = book totalDebt (average of the latest two balance sheets) as the market-value proxy)",
  },
  {
    path: "stageB.returns.notes.1",
    beforeMissing: true,
    after: "per-fiscal-year WACC unavailable: no fred:DGS10 observations supplied",
  },
  {
    path: "stageB.returns.wacc.erpAsOf",
    beforeMissing: true,
    after: "2026-07-06",
  },
  {
    path: "stageB.returns.wacc.erpSource",
    beforeMissing: true,
    after: "vendor",
  },
  {
    path: "stageB.returns.wacc.riskFreeSeriesId",
    beforeMissing: true,
    after: "fmp:treasury-rates.year10",
  },
  {
    path: "stageB.returns.wacc.taxRateBasis",
    beforeMissing: true,
    after: "FMP ratios effectiveTaxRate (observed effective rate)",
  },
  {
    path: "stageB.returns.waccHistory",
    beforeMissing: true,
    after: {"points":[],"missing":[{"date":"2023-12-31","reason":"no fred:DGS10 observations supplied"},{"date":"2024-12-31","reason":"no fred:DGS10 observations supplied"},{"date":"2025-12-31","reason":"no fred:DGS10 observations supplied"}],"basis":"per-fiscal-year WACC unavailable: no fred:DGS10 observations supplied","notes":["per-fiscal-year WACC unavailable: no fred:DGS10 observations supplied"],"gaps":[{"field":"returns.wacc.history","reason":"no fred:DGS10 observations supplied — ROIC-vs-WACC history compares every fiscal year to the current WACC","severity":"info","attemptedSources":["fred:DGS10"]}]},
  },
  {
    path: "stageB.returns.waccInputs",
    beforeMissing: true,
    after: {"waccPct":9.255946000000002,"riskFree":{"pct":4,"seriesId":"fmp:treasury-rates.year10","asOf":"2025-12-31"},"erp":{"pct":5,"source":"FMP market-risk-premium (US totalEquityRiskPremium)","asOf":"2026-07-06"},"beta":{"raw":1.1,"adjusted":1.0670000000000002,"final":1.0670000000000002,"method":"Blume-adjusted (0.67·raw + 0.33), clamped [0.6, 2]"},"costOfEquityPct":9.335,"costOfDebt":{"pct":12,"method":"effective","syntheticRating":null},"taxRate":{"fraction":0.2708333,"basis":"FMP ratios effectiveTaxRate (observed effective rate)"},"weights":{"equity":0.8648648648648649,"debt":0.13513513513513514,"basis":"market-value weights: equity = current market capitalization, debt = book totalDebt (average of the latest two balance sheets) as the market-value proxy"},"summary":"WACC 9.2559%: risk-free 4% (fmp:treasury-rates.year10, observation 2025-12-31); ERP 5% (FMP market-risk-premium (US totalEquityRiskPremium), as of 2026-07-06); beta 1.067 (Blume-adjusted (0.67·raw + 0.33), clamped [0.6, 2], raw 1.1); cost of equity 9.335%; pre-tax cost of debt 12% (effective); tax rate 27.0833% (FMP ratios effectiveTaxRate (observed effective rate)); E 86.4865% / D 13.5135% (market-value weights: equity = current market capitalization, debt = book totalDebt (average of the latest two balance sheets) as the market-value proxy)"},
  },
  {
    path: "stageB.scores.aspects.balanceSheet.drivers.2.value",
    before: 1.03,
    after: 0.89,
  },
  {
    path: "stageB.scores.aspects.balanceSheet.score",
    before: 78.65,
    after: 76.78,
  },
  {
    path: "stageB.scores.aspects.valuation.drivers.0.value",
    before: 265.58,
    after: 281.35,
  },
  {
    path: "stageB.valuation.assumptions.growthAnchor",
    beforeMissing: true,
    after: {"pointPct":9.105783594357353,"rangePct":[7.888888888888889,9.108945117996182],"methods":[{"name":"log-linear revenue regression","valuePct":9.102622070718525,"detail":"9.1%/yr fitted over 3 annual years (2023-12-31 to 2025-12-31), R2 1"},{"name":"3y revenue CAGR","valuePct":9.108945117996182,"detail":"9.11%"},{"name":"5y revenue CAGR","valuePct":9.108945117996182,"detail":"9.11%"},{"name":"analyst-consensus case","valuePct":7.888888888888889,"detail":"7.89% (average implied growth over the next 2 fiscal years, through 2027-12-31)"}],"unavailable":[],"basis":"median of 4 available growth methods = 9.11%, range 7.89% to 9.11% — methods: log-linear revenue regression 9.1%/yr fitted over 3 annual years (2023-12-31 to 2025-12-31), R2 1; 3y revenue CAGR 9.11%; 5y revenue CAGR 9.11%; analyst-consensus case 7.89% (average implied growth over the next 2 fiscal years, through 2027-12-31) (house rule, WS6 D-18: median of methods; the former \"lower of the 3y/5y CAGR\" and sign-disagreement rules are RETIRED)"},
  },
  {
    path: "stageB.valuation.assumptions.growthPath.basis",
    before: "linear fade from 7.89% (analyst consensus revenue, avg implied growth over next 2 fiscal years (through 2027-12-31)) to terminal 2.5% by year 10",
    after: "linear fade over the explicit 10-year horizon from 9.11% (median of the available growth methods (log-linear revenue regression 9.1%, 3y revenue CAGR 9.11%, 5y revenue CAGR 9.11%, analyst-consensus case 7.89%)) to the terminal rate 2.5% in year 10; median of 4 available growth methods = 9.11%, range 7.89% to 9.11% — methods: log-linear revenue regression 9.1%/yr fitted over 3 annual years (2023-12-31 to 2025-12-31), R2 1; 3y revenue CAGR 9.11%; 5y revenue CAGR 9.11%; analyst-consensus case 7.89% (average implied growth over the next 2 fiscal years, through 2027-12-31) (house rule, WS6 D-18: median of methods; the former \"lower of the 3y/5y CAGR\" and sign-disagreement rules are RETIRED)",
  },
  {
    path: "stageB.valuation.assumptions.growthPath.value.0",
    before: 7.888888888888889,
    after: 9.105783594357353,
  },
  {
    path: "stageB.valuation.assumptions.growthPath.value.1",
    before: 7.290123456790123,
    after: 8.37180763942876,
  },
  {
    path: "stageB.valuation.assumptions.growthPath.value.2",
    before: 6.691358024691358,
    after: 7.6378316845001635,
  },
  {
    path: "stageB.valuation.assumptions.growthPath.value.3",
    before: 6.092592592592593,
    after: 6.9038557295715695,
  },
  {
    path: "stageB.valuation.assumptions.growthPath.value.4",
    before: 5.493827160493828,
    after: 6.169879774642974,
  },
  {
    path: "stageB.valuation.assumptions.growthPath.value.5",
    before: 4.895061728395062,
    after: 5.43590381971438,
  },
  {
    path: "stageB.valuation.assumptions.growthPath.value.6",
    before: 4.296296296296296,
    after: 4.701927864785785,
  },
  {
    path: "stageB.valuation.assumptions.growthPath.value.7",
    before: 3.697530864197531,
    after: 3.96795190985719,
  },
  {
    path: "stageB.valuation.assumptions.growthPath.value.8",
    before: 3.098765432098766,
    after: 3.233975954928595,
  },
  {
    path: "stageB.valuation.assumptions.notes.0",
    before: "EBIT margin regime improving: dated 5y slope 1pp/year; target 20% versus current 20% and median 19%",
    after: "Near-term growth anchor: median of 4 available growth methods = 9.11%, range 7.89% to 9.11% — methods: log-linear revenue regression 9.1%/yr fitted over 3 annual years (2023-12-31 to 2025-12-31), R2 1; 3y revenue CAGR 9.11%; 5y revenue CAGR 9.11%; analyst-consensus case 7.89% (average implied growth over the next 2 fiscal years, through 2027-12-31) (house rule, WS6 D-18: median of methods; the former \"lower of the 3y/5y CAGR\" and sign-disagreement rules are RETIRED)",
  },
  {
    path: "stageB.valuation.assumptions.notes.2",
    beforeMissing: true,
    after: "terminal ROIC held at WACC: 2 fiscal years of ROIC on record, 4 needed to evidence durable excess returns (house convention)",
  },
  {
    path: "stageB.valuation.assumptions.notes.3",
    beforeMissing: true,
    after: "ROIC-vs-WACC history compares every fiscal year to the CURRENT WACC 9.26% — no per-year risk-free observation was available to recompute a year-specific WACC",
  },
  {
    path: "stageB.valuation.assumptions.notes.4",
    beforeMissing: true,
    after: "Stock-based compensation is expensed inside the EBIT this DCF projects, so it is never added back here; the reported free-cash-flow metric subtracts it as well (house default). The FCFF path derives from revenue, EBIT margin and reinvestment, not from the free-cash-flow metric, so the two are consistent but not the same series. Reported free cash flow as of 2025-12-31: 1800000000 before SBC → 1550000000 after subtracting SBC of 250000000.",
  },
  {
    path: "stageB.valuation.assumptions.sbc",
    beforeMissing: true,
    after: {"value":{"beforeSbc":1800000000,"afterSbc":1550000000,"sbc":250000000,"asOf":"2025-12-31","basis":"Free cash flow = operating cash flow + capital expenditure (FMP capex negative), MINUS stock-based compensation (house default: SBC is a cash-equivalent operating expense settled in shares, not a genuine add-back — Damodaran, \"Stock Based Compensation: The Elephant in the Room\"). Both the before- and after-SBC figures are reported; years with no disclosed SBC are unadjusted and say so."},"basis":"Stock-based compensation is expensed inside the EBIT this DCF projects, so it is never added back here; the reported free-cash-flow metric subtracts it as well (house default). The FCFF path derives from revenue, EBIT margin and reinvestment, not from the free-cash-flow metric, so the two are consistent but not the same series. Reported free cash flow as of 2025-12-31: 1800000000 before SBC → 1550000000 after subtracting SBC of 250000000."},
  },
  {
    path: "stageB.valuation.assumptions.terminal.roicTermPct.basis",
    before: "terminal ROIC = WACC (zero excess returns in perpetuity, house-rule default)",
    after: "terminal ROIC = WACC (zero excess returns in perpetuity, HOUSE CONVENTION default — see docs/METHODOLOGY.md, \"Terminal value house convention\"); ROIC-vs-WACC history compares every fiscal year to the CURRENT WACC 9.26% — no per-year risk-free observation was available to recompute a year-specific WACC",
  },
  {
    path: "stageB.valuation.assumptions.wacc",
    beforeMissing: true,
    after: {"value":9.255946000000002,"basis":"WACC 9.2559%: risk-free 4% (fmp:treasury-rates.year10, observation 2025-12-31); ERP 5% (FMP market-risk-premium (US totalEquityRiskPremium), as of 2026-07-06); beta 1.067 (Blume-adjusted (0.67·raw + 0.33), clamped [0.6, 2], raw 1.1); cost of equity 9.335%; pre-tax cost of debt 12% (effective); tax rate 27.0833% (FMP ratios effectiveTaxRate (observed effective rate)); E 86.4865% / D 13.5135% (market-value weights: equity = current market capitalization, debt = book totalDebt (average of the latest two balance sheets) as the market-value proxy)"},
  },
  {
    path: "stageB.valuation.dcf.enterpriseValue",
    before: 28677760654.031258,
    after: 29870645011.92904,
  },
  {
    path: "stageB.valuation.dcf.equityValue",
    before: 29977760654.031258,
    after: 31270645011.92904,
  },
  {
    path: "stageB.valuation.dcf.perShare",
    before: 146.23297880015247,
    after: 152.5397317655075,
  },
  {
    path: "stageB.valuation.dcf.pvExplicit",
    before: 14200057180.89785,
    after: 14543363972.145136,
  },
  {
    path: "stageB.valuation.dcf.pvTerminal",
    before: 14477703473.133406,
    after: 15327281039.783903,
  },
  {
    path: "stageB.valuation.dcf.terminalShare",
    before: 0.5048407945024906,
    after: 0.5131218637449192,
  },
  {
    path: "stageB.valuation.dcf.terminalValue",
    before: 33568192262.428688,
    after: 35538033898.713974,
  },
  {
    path: "stageB.valuation.dcf.yearRows.0.ebit",
    before: 2697222222.2222223,
    after: 2727644589.8589344,
  },
  {
    path: "stageB.valuation.dcf.yearRows.0.fcff",
    before: 1595946759.2592597,
    after: 1560935684.5040107,
  },
  {
    path: "stageB.valuation.dcf.yearRows.0.growthPct",
    before: 7.888888888888889,
    after: 9.105783594357353,
  },
  {
    path: "stageB.valuation.dcf.yearRows.0.nopat",
    before: 1966724537.0370374,
    after: 1988907513.4388065,
  },
  {
    path: "stageB.valuation.dcf.yearRows.0.pv",
    before: 1526848189.0941052,
    after: 1493352963.9068303,
  },
  {
    path: "stageB.valuation.dcf.yearRows.0.reinvestment",
    before: 370777777.7777776,
    after: 427971828.934796,
  },
  {
    path: "stageB.valuation.dcf.yearRows.0.revenue",
    before: 13486111111.11111,
    after: 13638222949.29467,
  },
  {
    path: "stageB.valuation.dcf.yearRows.1.ebit",
    before: 2893853052.1262,
    after: 2955997748.0092096,
  },
  {
    path: "stageB.valuation.dcf.yearRows.1.fcff",
    before: 1741252142.392903,
    after: 1726945549.1430979,
  },
  {
    path: "stageB.valuation.dcf.yearRows.1.growthPct",
    before: 7.290123456790123,
    after: 8.37180763942876,
  },
  {
    path: "stageB.valuation.dcf.yearRows.1.nopat",
    before: 2110918102.6123817,
    after: 2156249486.4656157,
  },
  {
    path: "stageB.valuation.dcf.yearRows.1.pv",
    before: 1524733847.0201824,
    after: 1512206225.9867628,
  },
  {
    path: "stageB.valuation.dcf.yearRows.1.reinvestment",
    before: 369665960.2194786,
    after: 429303937.3225178,
  },
  {
    path: "stageB.valuation.dcf.yearRows.1.revenue",
    before: 14469265260.631,
    after: 14779988740.046047,
  },
  {
    path: "stageB.valuation.dcf.yearRows.2.ebit",
    before: 3087491120.5524225,
    after: 3181771880.599768,
  },
  {
    path: "stageB.valuation.dcf.yearRows.2.fcff",
    before: 1888999203.554957,
    after: 1897383020.3386025,
  },
  {
    path: "stageB.valuation.dcf.yearRows.2.growthPct",
    before: 6.691358024691358,
    after: 7.6378316845001635,
  },
  {
    path: "stageB.valuation.dcf.yearRows.2.nopat",
    before: 2253038772.1962547,
    after: 2321838389.608853,
  },
  {
    path: "stageB.valuation.dcf.yearRows.2.pv",
    before: 1513976278.1400638,
    after: 1520695656.1614122,
  },
  {
    path: "stageB.valuation.dcf.yearRows.2.reinvestment",
    before: 364039568.6412978,
    after: 424455369.2702502,
  },
  {
    path: "stageB.valuation.dcf.yearRows.2.revenue",
    before: 15437455602.762112,
    after: 15908859402.99884,
  },
  {
    path: "stageB.valuation.dcf.yearRows.3.ebit",
    before: 3275599375.860153,
    after: 3401436820.8804526,
  },
  {
    path: "stageB.valuation.dcf.yearRows.3.fcff",
    before: 2037588409.2147698,
    after: 2070124881.4448662,
  },
  {
    path: "stageB.valuation.dcf.yearRows.3.growthPct",
    before: 6.092592592592593,
    after: 6.9038557295715695,
  },
  {
    path: "stageB.valuation.dcf.yearRows.3.nopat",
    before: 2391231929.193303,
    after: 2483094969.1725526,
  },
  {
    path: "stageB.valuation.dcf.yearRows.3.pv",
    before: 1494715972.3478506,
    after: 1518583788.0981958,
  },
  {
    path: "stageB.valuation.dcf.yearRows.3.reinvestment",
    before: 353643519.9785333,
    after: 412970087.72768646,
  },
  {
    path: "stageB.valuation.dcf.yearRows.3.revenue",
    before: 16377996879.300764,
    after: 17007184104.402262,
  },
  {
    path: "stageB.valuation.dcf.yearRows.4.ebit",
    before: 3455555144.040124,
    after: 3611301383.3392143,
  },
  {
    path: "stageB.valuation.dcf.yearRows.4.fcff",
    before: 2185260718.3870907,
    after: 2242773016.519078,
  },
  {
    path: "stageB.valuation.dcf.yearRows.4.growthPct",
    before: 5.493827160493828,
    after: 6.169879774642974,
  },
  {
    path: "stageB.valuation.dcf.yearRows.4.nopat",
    before: 2523577562.565436,
    after: 2637318393.9415503,
  },
  {
    path: "stageB.valuation.dcf.yearRows.4.pv",
    before: 1467237408.5221174,
    after: 1505852569.8890462,
  },
  {
    path: "stageB.valuation.dcf.yearRows.4.reinvestment",
    before: 338316844.1783454,
    after: 394545377.42247254,
  },
  {
    path: "stageB.valuation.dcf.yearRows.4.revenue",
    before: 17277775720.20062,
    after: 18056506916.69607,
  },
  {
    path: "stageB.valuation.dcf.yearRows.5.ebit",
    before: 3624706701.3996186,
    after: 3807608253.1775494,
  },
  {
    path: "stageB.valuation.dcf.yearRows.5.fcff",
    before: 2330126548.909354,
    after: 2412698436.7882514,
  },
  {
    path: "stageB.valuation.dcf.yearRows.5.growthPct",
    before: 4.895061728395062,
    after: 5.43590381971438,
  },
  {
    path: "stageB.valuation.dcf.yearRows.5.nopat",
    before: 2648131476.7452044,
    after: 2781755352.0843205,
  },
  {
    path: "stageB.valuation.dcf.yearRows.5.pv",
    before: 1431962215.2504165,
    after: 1482706164.5607312,
  },
  {
    path: "stageB.valuation.dcf.yearRows.5.reinvestment",
    before: 318004927.8358502,
    after: 369056915.29606915,
  },
  {
    path: "stageB.valuation.dcf.yearRows.5.revenue",
    before: 18123533506.998093,
    after: 19038041265.887745,
  },
  {
    path: "stageB.valuation.dcf.yearRows.6.ebit",
    before: 3780434841.163454,
    after: 3986639246.6155877,
  },
  {
    path: "stageB.valuation.dcf.yearRows.6.fcff",
    before: 2470201344.469651,
    after: 2577098620.742019,
  },
  {
    path: "stageB.valuation.dcf.yearRows.6.growthPct",
    before: 4.296296296296296,
    after: 4.701927864785785,
  },
  {
    path: "stageB.valuation.dcf.yearRows.6.nopat",
    before: 2762970247.2256613,
    after: 2913676888.405532,
  },
  {
    path: "stageB.valuation.dcf.yearRows.6.pv",
    before: 1389438480.1567645,
    after: 1449566044.012765,
  },
  {
    path: "stageB.valuation.dcf.yearRows.6.reinvestment",
    before: 292768902.75601006,
    after: 336578267.66351265,
  },
  {
    path: "stageB.valuation.dcf.yearRows.6.revenue",
    before: 18902174205.81727,
    after: 19933196233.077938,
  },
  {
    path: "stageB.valuation.dcf.yearRows.7.ebit",
    before: 3920217586.216349,
    after: 4144827174.7407875,
  },
  {
    path: "stageB.valuation.dcf.yearRows.7.fcff",
    before: 2603447020.008648,
    after: 2733066943.142533,
  },
  {
    path: "stageB.valuation.dcf.yearRows.7.growthPct",
    before: 3.697530864197531,
    after: 3.96795190985719,
  },
  {
    path: "stageB.valuation.dcf.yearRows.7.nopat",
    before: 2866238580.7080913,
    after: 3030460248.0179086,
  },
  {
    path: "stageB.valuation.dcf.yearRows.7.pv",
    before: 1340326582.9243398,
    after: 1407058506.9150107,
  },
  {
    path: "stageB.valuation.dcf.yearRows.7.reinvestment",
    before: 262791560.69944328,
    after: 297393304.8753758,
  },
  {
    path: "stageB.valuation.dcf.yearRows.7.revenue",
    before: 19601087931.081745,
    after: 20724135873.703938,
  },
  {
    path: "stageB.valuation.dcf.yearRows.8.ebit",
    before: 4041695933.6410785,
    after: 4278869888.9452515,
  },
  {
    path: "stageB.valuation.dcf.yearRows.8.fcff",
    before: 2727818246.380814,
    after: 2877672202.449499,
  },
  {
    path: "stageB.valuation.dcf.yearRows.8.growthPct",
    before: 3.098765432098766,
    after: 3.233975954928595,
  },
  {
    path: "stageB.valuation.dcf.yearRows.8.nopat",
    before: 2956197539.5393047,
    after: 3129672505.1538916,
  },
  {
    path: "stageB.valuation.dcf.yearRows.8.pv",
    before: 1285382062.9140253,
    after: 1355995120.5995789,
  },
  {
    path: "stageB.valuation.dcf.yearRows.8.reinvestment",
    before: 228379293.1584908,
    after: 252000302.70439225,
  },
  {
    path: "stageB.valuation.dcf.yearRows.8.revenue",
    before: 20208479668.20539,
    after: 21394349444.726257,
  },
  {
    path: "stageB.valuation.dcf.yearRows.9.ebit",
    before: 4142738331.982105,
    after: 4385841636.168883,
  },
  {
    path: "stageB.valuation.dcf.yearRows.9.fcff",
    before: 2841312241.349679,
    after: 3008045531.928512,
  },
  {
    path: "stageB.valuation.dcf.yearRows.9.nopat",
    before: 3031271950.2308083,
    after: 3209152416.708939,
  },
  {
    path: "stageB.valuation.dcf.yearRows.9.pv",
    before: 1225436144.5279837,
    after: 1297346932.014801,
  },
  {
    path: "stageB.valuation.dcf.yearRows.9.reinvestment",
    before: 189959708.88112947,
    after: 201106884.78042683,
  },
  {
    path: "stageB.valuation.dcf.yearRows.9.revenue",
    before: 20713691659.910522,
    after: 21929208180.844414,
  },
  {
    path: "stageB.valuation.gaps.2",
    beforeMissing: true,
    after: {"field":"valuation.dcf.terminalRoic.waccBasis","reason":"no per-fiscal-year risk-free observation was available, so the ROIC-vs-WACC evidence behind the terminal excess-return house convention compares every fiscal year to the CURRENT WACC","severity":"info"},
  },
  {
    path: "stageB.valuation.multiples.enterpriseValue",
    beforeMissing: true,
    after: {"value":6600000000,"excludingLeases":6600000000,"includingLeases":6700000000,"leaseLiability":100000000,"includeLeases":false,"basis":"Enterprise value EXCLUDES lease liabilities (house default; set THESIS_EV_INCLUDE_LEASES=1 to include them). EV = market cap + total debt + preferred stock + minority interest − cash and short-term investments, less lease liabilities of 100000000 (already inside totalDebt under FMP's definition). EV/EBITDA uses this same EV; EBITDA is AFTER operating-lease cost (US GAAP ASC 842 keeps it in operating expenses), so excluding the lease liability from EV keeps numerator and denominator on the same basis. EV excluding leases 6600000000; EV including leases 6700000000."},
  },
  {
    path: "stageB.valuation.multiples.multiples.1.basis",
    before: "EV (mcap + totalDebt + preferred + minority - cash&STI, latest quarterly balance sheet 2025-12-31) / (operatingIncome + D&A), latest annual FY 2025-12-31 — TTM suppressed-computed — vendor ebitda field not trusted",
    after: "EV / (operatingIncome + D&A), latest annual FY 2025-12-31 — TTM suppressed-computed — vendor ebitda field not trusted. Enterprise value EXCLUDES lease liabilities (house default; set THESIS_EV_INCLUDE_LEASES=1 to include them). EV = market cap + total debt + preferred stock + minority interest − cash and short-term investments, less lease liabilities of 100000000 (already inside totalDebt under FMP's definition). EV/EBITDA uses this same EV; EBITDA is AFTER operating-lease cost (US GAAP ASC 842 keeps it in operating expenses), so excluding the lease liability from EV keeps numerator and denominator on the same basis. EV excluding leases 6600000000; EV including leases 6700000000. Balance basis: latest quarterly balance sheet 2025-12-31.",
  },
  {
    path: "stageB.valuation.multiples.multiples.1.current",
    before: 2.392857142857143,
    after: 2.357142857142857,
  },
  {
    path: "stageB.valuation.multiples.multiples.2.basis",
    before: "EV / revenue (latest annual FY 2025-12-31 — TTM suppressed)",
    after: "EV / revenue (latest annual FY 2025-12-31 — TTM suppressed). Enterprise value EXCLUDES lease liabilities (house default; set THESIS_EV_INCLUDE_LEASES=1 to include them). EV = market cap + total debt + preferred stock + minority interest − cash and short-term investments, less lease liabilities of 100000000 (already inside totalDebt under FMP's definition). EV/EBITDA uses this same EV; EBITDA is AFTER operating-lease cost (US GAAP ASC 842 keeps it in operating expenses), so excluding the lease liability from EV keeps numerator and denominator on the same basis. EV excluding leases 6600000000; EV including leases 6700000000.",
  },
  {
    path: "stageB.valuation.multiples.multiples.2.current",
    before: 0.536,
    after: 0.528,
  },
  {
    path: "stageB.valuation.multiples.notes.3",
    beforeMissing: true,
    after: "cash-flow-derived multiples use the latest ANNUAL statement — TTM was suppressed (incomplete quarterly data)",
  },
  {
    path: "stageB.valuation.notes.0",
    before: "EBIT margin regime improving: dated 5y slope 1pp/year; target 20% versus current 20% and median 19%",
    after: "Near-term growth anchor: median of 4 available growth methods = 9.11%, range 7.89% to 9.11% — methods: log-linear revenue regression 9.1%/yr fitted over 3 annual years (2023-12-31 to 2025-12-31), R2 1; 3y revenue CAGR 9.11%; 5y revenue CAGR 9.11%; analyst-consensus case 7.89% (average implied growth over the next 2 fiscal years, through 2027-12-31) (house rule, WS6 D-18: median of methods; the former \"lower of the 3y/5y CAGR\" and sign-disagreement rules are RETIRED)",
  },
  {
    path: "stageB.valuation.notes.3",
    beforeMissing: true,
    after: "ROIC-vs-WACC history compares every fiscal year to the CURRENT WACC 9.26% — no per-year risk-free observation was available to recompute a year-specific WACC",
  },
  {
    path: "stageB.valuation.notes.4",
    beforeMissing: true,
    after: "Stock-based compensation is expensed inside the EBIT this DCF projects, so it is never added back here; the reported free-cash-flow metric subtracts it as well (house default). The FCFF path derives from revenue, EBIT margin and reinvestment, not from the free-cash-flow metric, so the two are consistent but not the same series. Reported free cash flow as of 2025-12-31: 1800000000 before SBC → 1550000000 after subtracting SBC of 250000000.",
  },
  {
    path: "stageB.valuation.notes.5",
    beforeMissing: true,
    after: "DCF equity bridge: EV − net debt − minority interest − preferred equity. Net debt including leases -1300000000; excluding leases -1400000000; EXCLUDING lease liabilities of 100000000 (house default excludes them; THESIS_EV_INCLUDE_LEASES=1 includes them).",
  },
  {
    path: "stageB.valuation.notes.6",
    beforeMissing: true,
    after: "NET_DEBT_V1: net debt -1300000000 as of 2025-12-31; totalDebt 1200000000, cashAndShortTermInvestments 2500000000",
  },
  {
    path: "stageB.valuation.reverseDcf.impliedRevenueGrowthPct",
    before: -17.24609375,
    after: -17.5,
  },
  {
    path: "stageB.valuation.sensitivity.perShare.0.0",
    before: 166.376092292583,
    after: 173.8049998521903,
  },
  {
    path: "stageB.valuation.sensitivity.perShare.0.1",
    before: 167.7149851175111,
    after: 175.22246130579066,
  },
  {
    path: "stageB.valuation.sensitivity.perShare.0.2",
    before: 169.2211734983775,
    after: 176.81703551814675,
  },
  {
    path: "stageB.valuation.sensitivity.perShare.0.3",
    before: 170.9424020912171,
    after: 178.63926888721124,
  },
  {
    path: "stageB.valuation.sensitivity.perShare.0.4",
    before: 172.94649343185347,
    after: 180.76096389666722,
  },
  {
    path: "stageB.valuation.sensitivity.perShare.1.0",
    before: 155.24133879734714,
    after: 162.0471351684362,
  },
  {
    path: "stageB.valuation.sensitivity.perShare.1.1",
    before: 156.0003561762538,
    after: 162.8506930463946,
  },
  {
    path: "stageB.valuation.sensitivity.perShare.1.2",
    before: 156.82318027878264,
    after: 163.72180194078325,
  },
  {
    path: "stageB.valuation.sensitivity.perShare.1.3",
    before: 157.72643914234646,
    after: 164.67806565202787,
  },
  {
    path: "stageB.valuation.sensitivity.perShare.1.4",
    before: 158.73308812865395,
    after: 165.74378660357115,
  },
  {
    path: "stageB.valuation.sensitivity.perShare.2.0",
    before: 145.54397447067558,
    after: 151.8102954280996,
  },
  {
    path: "stageB.valuation.sensitivity.perShare.2.1",
    before: 145.888476635414,
    after: 152.17501359680358,
  },
  {
    path: "stageB.valuation.sensitivity.perShare.2.2",
    before: 146.23297880015247,
    after: 152.5397317655075,
  },
  {
    path: "stageB.valuation.sensitivity.perShare.2.3",
    before: 146.57748096489092,
    after: 152.9044499342115,
  },
  {
    path: "stageB.valuation.sensitivity.perShare.2.4",
    before: 146.92198312962938,
    after: 153.26916810291547,
  },
  {
    path: "stageB.valuation.sensitivity.perShare.3.0",
    before: 137.02303327015306,
    after: 142.81822308027702,
  },
  {
    path: "stageB.valuation.sensitivity.perShare.3.1",
    before: 137.07019569277645,
    after: 142.86815307831895,
  },
  {
    path: "stageB.valuation.sensitivity.perShare.3.2",
    before: 137.07839478363584,
    after: 142.87683330651296,
  },
  {
    path: "stageB.valuation.sensitivity.perShare.3.3",
    before: 137.03897964504117,
    after: 142.83510521700046,
  },
  {
    path: "stageB.valuation.sensitivity.perShare.3.4",
    before: 136.940533723176,
    after: 142.7308823121421,
  },
  {
    path: "stageB.valuation.sensitivity.perShare.4.0",
    before: 129.477139616909,
    after: 134.8577470549213,
  },
  {
    path: "stageB.valuation.sensitivity.perShare.4.1",
    before: 129.31120340693457,
    after: 134.68207341098494,
  },
  {
    path: "stageB.valuation.sensitivity.perShare.4.2",
    before: 129.08313762406544,
    after: 134.44062431955413,
  },
  {
    path: "stageB.valuation.sensitivity.perShare.4.3",
    before: 128.78009840764705,
    after: 134.11980221922994,
  },
  {
    path: "stageB.valuation.sensitivity.perShare.4.4",
    before: 128.38543965803257,
    after: 133.70198418742842,
  },
  // ---- WS6 (valuation inputs and disclosure) ---- END
];

const PROVIDER_ENV_KEYS = [
  "FMP_API_KEY",
  "FINNHUB_API_KEY",
  "FRED_API_KEY",
  "ANTHROPIC_API_KEY",
  "EDGAR_CONTACT",
] as const;

function generatorChildEnv(): NodeJS.ProcessEnv {
  const controlled = new Set([
    ...PROVIDER_ENV_KEYS.map((key) => key.toLowerCase()),
    "audit_fixture_emit",
    "audit_fixture_output",
    "node_options",
    "node_path",
  ]);
  const env: NodeJS.ProcessEnv = { ...process.env };
  for (const key of Object.keys(env)) {
    if (controlled.has(key.toLowerCase())) delete env[key];
  }
  env.AUDIT_FIXTURE_EMIT = "1";
  env.NODE_OPTIONS = "--conditions=react-server";
  env.NODE_PATH = path.join(ROOT, "node_modules");
  return env;
}

function sha256File(file: string): string {
  return createHash("sha256").update(readFileSync(file)).digest("hex");
}

function fixtureTreeSha256(root: string): string {
  const visit = (dir: string): string[] =>
    readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
      const absolute = path.join(dir, entry.name);
      return entry.isDirectory() ? visit(absolute) : [absolute];
    });
  const files = visit(root)
    .filter((file) => file.endsWith(".json"))
    .map((file) => path.relative(root, file).replaceAll("\\", "/"))
    .sort();
  const hash = createHash("sha256");
  for (const relative of files) {
    hash.update(relative);
    hash.update("\0");
    hash.update(readFileSync(path.join(root, ...relative.split("/"))));
    hash.update("\0");
  }
  return hash.digest("hex");
}

function loadBaseline(): BaselineDocument {
  return JSON.parse(readFileSync(BASELINE_PATH, "utf8")) as BaselineDocument;
}

function isRecord(value: JsonValue): value is { [key: string]: JsonValue } {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function diffPaths(before: JsonValue, after: JsonValue, prefix = ""): string[] {
  if (Array.isArray(before) && Array.isArray(after)) {
    const paths: string[] = [];
    const sharedLength = Math.min(before.length, after.length);
    for (let index = 0; index < sharedLength; index++) {
      paths.push(...diffPaths(before[index], after[index], `${prefix}.${index}`));
    }
    for (let index = sharedLength; index < Math.max(before.length, after.length); index++) {
      paths.push(`${prefix}.${index}`);
    }
    return paths;
  }
  if (Array.isArray(before) || Array.isArray(after)) return [prefix];
  if (isRecord(before) && isRecord(after)) {
    const keys = [...new Set([...Object.keys(before), ...Object.keys(after)])].sort();
    return keys.flatMap((key) => {
      const child = prefix.length > 0 ? `${prefix}.${key}` : key;
      if (!(key in before) || !(key in after)) return [child];
      return diffPaths(before[key], after[key], child);
    });
  }
  return Object.is(before, after) ? [] : [prefix];
}

function canonicalJson(value: JsonValue): string {
  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`;
  if (isRecord(value)) {
    return `{${Object.keys(value)
      .sort()
      .map((key) => `${JSON.stringify(key)}:${canonicalJson(value[key])}`)
      .join(",")}}`;
  }
  return JSON.stringify(value);
}

function readJsonPath(
  root: JsonValue,
  dottedPath: string,
): { exists: boolean; value: JsonValue | undefined } {
  let cursor: JsonValue = root;
  for (const key of dottedPath.split(".")) {
    if (Array.isArray(cursor)) {
      const index = Number(key);
      if (!Number.isInteger(index) || index < 0 || index >= cursor.length) {
        return { exists: false, value: undefined };
      }
      cursor = cursor[index];
      continue;
    }
    if (!isRecord(cursor) || !Object.hasOwn(cursor, key)) {
      return { exists: false, value: undefined };
    }
    cursor = cursor[key];
  }
  return { exists: true, value: cursor };
}

function assertExactDeltaContract(before: JsonValue, after: JsonValue): void {
  const actual = diffPaths(before, after).sort();
  const expected = INTENDED_DELTAS.map((delta) => delta.path).sort();
  if (JSON.stringify(actual) !== JSON.stringify(expected)) {
    throw new Error(
      `fixture delta contract mismatch\nexpected=${JSON.stringify(expected)}\nactual=${JSON.stringify(actual)}`,
    );
  }

  const reconstructed = structuredClone(before);
  for (const delta of INTENDED_DELTAS) {
    const baselineValue = readJsonPath(before, delta.path);
    if ("beforeMissing" in delta) {
      if (baselineValue.exists) {
        throw new Error(`expected audited path to be absent: ${delta.path}`);
      }
    } else if (
      !baselineValue.exists ||
      canonicalJson(baselineValue.value!) !== canonicalJson(delta.before)
    ) {
      throw new Error(`unexpected audited value at ${delta.path}`);
    }
    const currentValue = readJsonPath(after, delta.path);
    if (
      !currentValue.exists ||
      canonicalJson(currentValue.value!) !== canonicalJson(delta.after)
    ) {
      throw new Error(`unexpected current value at ${delta.path}`);
    }
    setJsonPath(reconstructed, delta.path, delta.after);
  }
  if (canonicalJson(reconstructed) !== canonicalJson(after)) {
    throw new Error("current projection differs from audited baseline plus exact intended deltas");
  }
}

function setJsonPath(root: JsonValue, dottedPath: string, value: JsonValue): void {
  const keys = dottedPath.split(".");
  let cursor = root;
  for (const key of keys.slice(0, -1)) {
    if (Array.isArray(cursor)) {
      const index = Number(key);
      if (!Number.isInteger(index) || index < 0 || index >= cursor.length) {
        throw new Error(`missing JSON path ${dottedPath}`);
      }
      cursor = cursor[index];
    } else {
      if (!isRecord(cursor) || !(key in cursor)) {
        throw new Error(`missing JSON path ${dottedPath}`);
      }
      cursor = cursor[key];
    }
  }
  const finalKey = keys.at(-1)!;
  if (Array.isArray(cursor)) {
    const index = Number(finalKey);
    if (!Number.isInteger(index) || index < 0 || index > cursor.length) {
      throw new Error(`missing JSON path ${dottedPath}`);
    }
    if (index === cursor.length) cursor.push(value);
    else cursor[index] = value;
  } else {
    if (!isRecord(cursor)) throw new Error(`non-object JSON parent ${dottedPath}`);
    cursor[finalKey] = value;
  }
}

afterEach(() => {
  vi.unstubAllEnvs();
  vi.unstubAllGlobals();
  vi.restoreAllMocks();
});

describe("Task 32 provider-free historical fixture comparison", () => {
  it("pins audited provenance, current fixture bytes, and the exact intended delta allowlist", async () => {
    const baseline = loadBaseline();
    expect(baseline.provenance).toMatchObject({
      auditedBaseCommit: "524d09e81b00b08fe6af386011d34759a5e02fc0",
      auditedBaseTree: AUDITED_BASE_TREE,
      fixedNow: FIXED_NOW,
      generatedAt: GENERATED_AT,
      fixtureHashes: {
        fmpTreeSha256: AUDITED_FMP_TREE_SHA256,
        reportSha256: AUDITED_REPORT_SHA256,
      },
      generator: {
        helperSha256: "73e890f2ec86463f5c86cb220e7ee65c8955ba4e0fdcbbc7eea6baff5e035bfe",
        basePackageLockBlob: "66f7242846b6d20cfe99e21400d2dada27bbfbfd",
        comparisonPackageLockBlob: "58d0f8390e3ee80281eec42f1dce8133f8d7daf2",
        generationNode: "v24.11.1",
        generationNpm: "11.6.2",
        command:
          "in detached 524d09e: npm ci; provider env blank; NODE_OPTIONS=--conditions=react-server; NODE_PATH=<base>/node_modules; AUDIT_FIXTURE_EMIT=1; node <base>/node_modules/tsx/dist/cli.mjs - < <remediation>/tests/helpers/auditFixtureComparison.ts",
      },
    });
    expect(baseline.provenance.sourceBlobs).toEqual({
      "src/pipeline/dataBundle.ts": "ca2efa5a8b191a45eb879142d5ec738777691eaf",
      "src/pipeline/compute.ts": "835d6dab9b892fbb9905fd3393a7600215e9c3ab",
      "src/pipeline/stageC/passes.ts": "11b36ed190e872c27621c0c79dbd34bb4a9b43da",
      "src/report/schema.ts": "891d66275b154aa2b4f1f1b32961382eaa0e72ad",
    });
    expect(
      execFileSync("git", ["hash-object", "package-lock.json"], {
        cwd: ROOT,
        encoding: "utf8",
      }).trim(),
    ).toBe(baseline.provenance.generator.comparisonPackageLockBlob);
    expect(sha256File(GENERATOR_PATH)).toBe(
      baseline.provenance.generator.helperSha256,
    );
    expect(fixtureTreeSha256(FMP_FIXTURE_ROOT)).toBe(AUDITED_FMP_TREE_SHA256);
    expect(sha256File(REPORT_FIXTURE)).toBe(AUDITED_REPORT_SHA256);

    for (const key of PROVIDER_ENV_KEYS) vi.stubEnv(key, "");
    vi.stubEnv("AUDIT_FIXTURE_EMIT", "");
    vi.stubEnv("AUDIT_FIXTURE_OUTPUT", "");
    const { assertAuditJsonSafe, buildAuditFixtureComparison } = await import(
      "./helpers/auditFixtureComparison"
    );
    const result = await buildAuditFixtureComparison({
      fmpFixtures: FMP_FIXTURE_ROOT,
      reportFixture: REPORT_FIXTURE,
    });
    const current = result.projection;
    expect(result.repeatedProjection).toEqual(current);
    const emitted = execFileSync(
      process.execPath,
      [path.join(ROOT, "node_modules", "tsx", "dist", "cli.mjs"), "-"],
      {
        cwd: ROOT,
        encoding: "utf8",
        env: generatorChildEnv(),
        input: readFileSync(GENERATOR_PATH, "utf8"),
        maxBuffer: 4 * 1024 * 1024,
        timeout: 20_000,
      },
    );
    expect(JSON.parse(emitted) as JsonValue).toEqual(current);
    expect(JSON.stringify(current)).toContain('"$auditUndefined":true');
    expect(() => assertAuditJsonSafe({ invalid: Number.NaN })).toThrow(
      /non-finite number.*invalid/,
    );
    expect(() => assertAuditJsonSafe({ invalid: undefined })).toThrow(
      /non-JSON undefined.*invalid/,
    );
    expect(() => assertAuditJsonSafe({ invalid: new Date(0) })).toThrow(
      /non-plain object.*invalid/,
    );
    expect(() => assertAuditJsonSafe({ invalid: new Map([["value", 1]]) })).toThrow(
      /non-plain object.*invalid/,
    );
    const decoratedArray = [1];
    Object.assign(decoratedArray, { extra: 2 });
    expect(() => assertAuditJsonSafe({ invalid: decoratedArray })).toThrow(
      /non-canonical array property.*invalid/,
    );
    assertExactDeltaContract(baseline.projection, current);
    expect(INTENDED_DELTAS.length).toBeGreaterThan(0);
    expect(result.calls).toMatchObject({
      globalFetch: 0,
      fmpLiveFetch: 0,
      finnhubLiveFetch: 0,
    });
    expect(result.calls.finraGapTransport).toBeGreaterThan(0);
    expect(result.calls.edgarGapTransport).toBeGreaterThan(0);
    expect(result.calls.fredGap).toBeGreaterThan(0);
    expect(result.reportCostUsd).toBe(0);
    expect(result.reportModel).toBe("synthetic-fixture");

    const unlistedDrift = structuredClone(current);
    setJsonPath(unlistedDrift, "fixtureControl.quotePrice", 41);
    expect(() => assertExactDeltaContract(baseline.projection, unlistedDrift)).toThrow(
      /fixtureControl\.quotePrice/,
    );

    const missingIntendedDelta = structuredClone(current);
    const baselineRatio = (baseline.projection as {
      stageB: { technicals: { volumeTrend: { ratio: JsonValue } } };
    }).stageB.technicals.volumeTrend.ratio;
    setJsonPath(
      missingIntendedDelta,
      "stageB.technicals.volumeTrend.ratio",
      baselineRatio,
    );
    expect(() =>
      assertExactDeltaContract(baseline.projection, missingIntendedDelta),
    ).toThrow(/stageB\.technicals\.volumeTrend\.ratio/);

    const arbitraryAllowedPathDrift = structuredClone(current);
    setJsonPath(
      arbitraryAllowedPathDrift,
      "stageB.technicals.volumeTrend.ratio",
      99,
    );
    expect(() =>
      assertExactDeltaContract(baseline.projection, arbitraryAllowedPathDrift),
    ).toThrow(/unexpected current value.*stageB\.technicals\.volumeTrend\.ratio/);
  }, 30_000);
});
