/**
 * Generate the README's cost tables from the model registry and the code that
 * sizes reservations. No network, no provider call.
 *
 *   npm run docs:pricing            # print the tables
 *   npm run docs:pricing -- --write # rewrite the marked README block
 *
 * The block is delimited by the markers below so a doc-lint test can prove the
 * committed README still matches what the code computes.
 */

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { isEntryPoint } from "./lib/entrypoint.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const README_PATH = path.join(HERE, "..", "README.md");
export const BEGIN_MARKER = "<!-- BEGIN GENERATED: pricing -->";
export const END_MARKER = "<!-- END GENERATED: pricing -->";

/**
 * Effort the fixture shape's output counts were measured at. Effort is the user's
 * cost knob (settings -> analysis effort) and the runner's default when nothing is
 * set. The shape below is NOT re-derived per effort: there are no measured token
 * counts at the other levels, and inventing multipliers would make this table look
 * precise without making it accurate.
 */
export const FIXTURE_RUN_EFFORT = "high";

/** Shape of one fixture-run request, used for the estimate column. */
export const FIXTURE_RUN_SHAPE = {
  passes: [
    { pass: "bull", inputTokens: 90_000, cacheWriteTokens: 75_000, cacheReadTokens: 0, outputTokens: 9_000, webSearches: 4 },
    { pass: "bear", inputTokens: 15_000, cacheWriteTokens: 0, cacheReadTokens: 90_000, outputTokens: 9_000, webSearches: 4 },
    { pass: "synthesize", inputTokens: 20_000, cacheWriteTokens: 0, cacheReadTokens: 90_000, outputTokens: 25_000, webSearches: 0 },
  ],
};

const usd = (value) => `$${value.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

/** Estimated end-to-end cost of one run of the fixture shape on a model. */
export function estimateRunCostUsd(registryModel, judgeModel, webSearchUsdPerSearch) {
  let total = 0;
  for (const pass of FIXTURE_RUN_SHAPE.passes) {
    const entry = pass.pass === "synthesize" ? judgeModel : registryModel;
    const p = entry.pricing;
    total +=
      (pass.inputTokens / 1e6) * p.inputPerMTok +
      (pass.cacheWriteTokens / 1e6) * p.cacheWrite5mPerMTok +
      (pass.cacheReadTokens / 1e6) * p.cacheReadPerMTok +
      (pass.outputTokens / 1e6) * p.outputPerMTok +
      pass.webSearches * webSearchUsdPerSearch;
  }
  return total;
}

/**
 * Output ceiling one pass may emit at a given effort, from the code that sizes it
 * (`effectiveMaxTokens`): below `high` the pass constant applies; at `high` and
 * above max_tokens is raised to the model's registry ceiling. This is the part of
 * per-effort cost that is derivable rather than guessed, and it is the step that
 * makes a `max` run on an expensive model cost multiples of the same run at `low`.
 */
export function outputCeilingTokens(registryModel, pass, effort, sizing) {
  const { analystMaxTokens, judgeMaxTokens, isHighOrAboveEffort } = sizing;
  if (isHighOrAboveEffort(effort)) return registryModel.maxOutputTokens;
  return pass === "synthesize" ? judgeMaxTokens : analystMaxTokens;
}

export function renderPricingBlock(registry, sizing) {
  const { maximumRequestCostUsd, passWorstCaseCostUsd, maxRequestsPerPass } = sizing;
  const active = registry.models.filter((m) => m.lifecycle === "active");
  const judge = active.find((m) => m.id === registry.judgeFloorModelId);
  if (!judge) throw new Error("Pricing documentation requires an active judge floor model");
  const searchUsd = registry.webSearchUsdPerThousand / 1000;

  const lines = [];
  lines.push(BEGIN_MARKER);
  lines.push("");
  lines.push(`Registry snapshot ${registry.snapshotDate}, generated by \`npm run docs:pricing\``);
  lines.push("from `config/models.json` and the reservation code. Each request is admitted");
  lines.push("against spend caps using up to ten input contexts per search-enabled model,");
  lines.push("at five-minute cache-write rates, plus output and configured fallback exposure.");
  lines.push("Analyst requests also reserve eight $0.01 searches; the judge never searches.");
  lines.push("");
  lines.push("| Analysis model | One analyst request | One synthesize request | Analyst pass worst case | Primary output ceiling | Estimated run |");
  lines.push("| --- | ---: | ---: | ---: | ---: | ---: |");
  for (const model of active) {
    const judgeEntry = model.family === "haiku" ? judge : model;
    const ceiling = (effort) =>
      usd((outputCeilingTokens(model, "bull", effort, sizing) / 1e6) * model.pricing.outputPerMTok);
    const step = ceiling("low") === ceiling("high") ? ceiling("low") : `${ceiling("low")} → ${ceiling("high")}`;
    lines.push(
      `| ${model.displayName} | ${usd(maximumRequestCostUsd(model.id, "bull"))} | ` +
      `${usd(maximumRequestCostUsd(model.id, "synthesize"))} | ` +
      `${usd(passWorstCaseCostUsd(model.id, "bull"))} | ${step} | ` +
      `${usd(estimateRunCostUsd(model, judgeEntry, searchUsd))} |`,
    );
  }
  lines.push("");
  lines.push(`The worst case is every request one pass could make (${maxRequestsPerPass}: six transport attempts,`);
  lines.push("each able to pause and resume five times); in the default request mode it is");
  lines.push("reported, not reserved, so a job cap need only cover the requests in flight, while");
  lines.push("`THESIS_RESERVATION_MODE=pass` reserves it whole. Neither reservation column varies");
  lines.push("with effort — both bound a request at the model's full context and output ceiling.");
  lines.push("");
  lines.push("The primary-model output ceiling varies with effort; thinking bills as output.");
  lines.push("Below `high`, passes use analyst 64K/judge 96K; at `high` and above, the model's");
  lines.push("registry ceiling applies. Fallback output is additional and covered by request");
  lines.push("reservations. Abandoned search/fallback requests retain their presumed bound.");
  lines.push("");
  lines.push("The estimated run is a calculation, not a measurement: the fixture shape at effort");
  lines.push(`\`${FIXTURE_RUN_EFFORT}\` and registry rates, Haiku's synthesize figures those of ${judge.displayName}`);
  lines.push("because that pass is raised to it. It does NOT scale with effort — usage at");
  lines.push("other levels has not been measured. Higher effort can consume more tokens;");
  lines.push("these examples are neither minimum nor maximum prices. New model quality and");
  lines.push("end-to-end costs have not been measured in live Thesis runs for this update.");
  lines.push("");
  lines.push(END_MARKER);
  return lines.join("\n");
}

export function replaceBlock(readme, block) {
  const begin = readme.indexOf(BEGIN_MARKER);
  const end = readme.indexOf(END_MARKER);
  if (begin < 0 || end < 0) {
    throw new Error(`README is missing the ${BEGIN_MARKER} / ${END_MARKER} markers`);
  }
  return readme.slice(0, begin) + block + readme.slice(end + END_MARKER.length);
}

async function main(argv) {
  const registry = JSON.parse(readFileSync(path.join(HERE, "..", "config", "models.json"), "utf8"));
  const provider = await import("../src/providers/anthropic.ts");
  const registryModule = await import("../src/models/registry.ts");
  const passes = await import("../src/pipeline/stageC/passes.ts");
  const block = renderPricingBlock(registry, {
    maximumRequestCostUsd: provider.maximumRequestCostUsd,
    passWorstCaseCostUsd: provider.passWorstCaseCostUsd,
    maxRequestsPerPass: provider.PASS_MAX_REQUESTS,
    isHighOrAboveEffort: registryModule.isHighOrAboveEffort,
    analystMaxTokens: passes.ANALYST_MAX_TOKENS,
    judgeMaxTokens: passes.JUDGE_MAX_TOKENS,
  });
  if (!argv.includes("--write")) {
    console.log(block);
    return 0;
  }
  const readme = readFileSync(README_PATH, "utf8");
  writeFileSync(README_PATH, replaceBlock(readme, block), "utf8");
  console.log(`docs:pricing — rewrote the generated block in ${README_PATH}`);
  return 0;
}

if (isEntryPoint(import.meta.url)) {
  main(process.argv.slice(2)).then(
    (code) => process.exit(code),
    (error) => {
      console.error(error instanceof Error ? error.message : String(error));
      process.exit(1);
    },
  );
}
