/**
 * Generate the README's cost tables from the model registry and the code that
 * sizes reservations. No network, no provider call.
 *
 *   npm run docs:pricing            # print the tables
 *   npm run docs:pricing -- --write # rewrite the marked README block
 *
 * The block is delimited by the markers below so a doc-lint test can prove the
 * committed README still matches what the code computes.
 */

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const README_PATH = path.join(HERE, "..", "README.md");
export const BEGIN_MARKER = "<!-- BEGIN GENERATED: pricing -->";
export const END_MARKER = "<!-- END GENERATED: pricing -->";

/** Shape of one fixture-run request, used for the estimate column. */
export const FIXTURE_RUN_SHAPE = {
  passes: [
    { pass: "bull", inputTokens: 90_000, cacheWriteTokens: 75_000, cacheReadTokens: 0, outputTokens: 9_000, webSearches: 4 },
    { pass: "bear", inputTokens: 15_000, cacheWriteTokens: 0, cacheReadTokens: 90_000, outputTokens: 9_000, webSearches: 4 },
    { pass: "synthesize", inputTokens: 20_000, cacheWriteTokens: 0, cacheReadTokens: 90_000, outputTokens: 25_000, webSearches: 0 },
  ],
};

const usd = (value) => `$${value.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

/** Estimated end-to-end cost of one run of the fixture shape on a model. */
export function estimateRunCostUsd(registryModel, judgeModel, webSearchUsdPerSearch) {
  let total = 0;
  for (const pass of FIXTURE_RUN_SHAPE.passes) {
    const entry = pass.pass === "synthesize" ? judgeModel : registryModel;
    const p = entry.pricing;
    total +=
      (pass.inputTokens / 1e6) * p.inputPerMTok +
      (pass.cacheWriteTokens / 1e6) * p.cacheWrite5mPerMTok +
      (pass.cacheReadTokens / 1e6) * p.cacheReadPerMTok +
      (pass.outputTokens / 1e6) * p.outputPerMTok +
      pass.webSearches * webSearchUsdPerSearch;
  }
  return total;
}

export function renderPricingBlock(registry, sizing) {
  const { maximumRequestCostUsd, passWorstCaseCostUsd, maxRequestsPerPass } = sizing;
  const active = registry.models.filter((m) => m.lifecycle === "active");
  const judge = active.find((m) => m.id === "claude-sonnet-5");
  const searchUsd = registry.webSearchUsdPerThousand / 1000;

  const lines = [];
  lines.push(BEGIN_MARKER);
  lines.push("");
  lines.push(`Registry snapshot ${registry.snapshotDate}, generated by \`npm run docs:pricing\``);
  lines.push("from `config/models.json` and the reservation code. Each request is admitted");
  lines.push("against the spend caps before it is sent, bounded by the model's full context");
  lines.push("window priced as a five-minute cache write, its maximum output, and eight web");
  lines.push("searches at $0.01 (the judge never searches).");
  lines.push("");
  lines.push("| Analysis model | One analyst request | One synthesize request | Analyst pass worst case | Estimated run |");
  lines.push("| --- | ---: | ---: | ---: | ---: |");
  for (const model of active) {
    const judgeEntry = model.family === "haiku" ? judge : model;
    lines.push(
      `| ${model.displayName} | ${usd(maximumRequestCostUsd(model.id, "bull"))} | ` +
      `${usd(maximumRequestCostUsd(model.id, "synthesize"))} | ` +
      `${usd(passWorstCaseCostUsd(model.id, "bull"))} | ` +
      `${usd(estimateRunCostUsd(model, judgeEntry, searchUsd))} |`,
    );
  }
  lines.push("");
  lines.push(`The worst case is every request one pass could make (${maxRequestsPerPass}: six transport attempts,`);
  lines.push("each able to pause and resume five times); it is reported, not reserved, so a");
  lines.push("job cap only has to cover the requests in flight. The estimate is a");
  lines.push("calculation, not a measurement: the fixture run shape at registry rates, with");
  lines.push("Haiku's synthesize figures those of Sonnet 5 because that pass is raised to");
  lines.push("it. One measured Haiku run settled at $1.43 in total.");
  lines.push("");
  lines.push(END_MARKER);
  return lines.join("\n");
}

export function replaceBlock(readme, block) {
  const begin = readme.indexOf(BEGIN_MARKER);
  const end = readme.indexOf(END_MARKER);
  if (begin < 0 || end < 0) {
    throw new Error(`README is missing the ${BEGIN_MARKER} / ${END_MARKER} markers`);
  }
  return readme.slice(0, begin) + block + readme.slice(end + END_MARKER.length);
}

async function main(argv) {
  const registry = JSON.parse(readFileSync(path.join(HERE, "..", "config", "models.json"), "utf8"));
  const provider = await import("../src/providers/anthropic.ts");
  const block = renderPricingBlock(registry, {
    maximumRequestCostUsd: provider.maximumRequestCostUsd,
    passWorstCaseCostUsd: provider.passWorstCaseCostUsd,
    maxRequestsPerPass: provider.PASS_MAX_REQUESTS,
  });
  if (!argv.includes("--write")) {
    console.log(block);
    return 0;
  }
  const readme = readFileSync(README_PATH, "utf8");
  writeFileSync(README_PATH, replaceBlock(readme, block), "utf8");
  console.log(`docs:pricing — rewrote the generated block in ${README_PATH}`);
  return 0;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main(process.argv.slice(2)).then(
    (code) => process.exit(code),
    (error) => {
      console.error(error instanceof Error ? error.message : String(error));
      process.exit(1);
    },
  );
}
